- OWNERS
mikdanese needs to approve changes to gke-certificates-controller which
will live in this repo.
mikedanese is:
* emeritus maintainer of gcp cloud provider.
* owner of k8s.io/kubernetes/pkg/cloudprovider.
> add mikedanese to owners

- cmd/gke-certificates-controller/app/BUILD
- cmd/gke-certificates-controller/app/gke_approver.go
- cmd/gke-certificates-controller/app/gke_approver_test.go
- discard warnings when parsing gce.conf
- get instance name from csr.Spec.Username (instead of DNS SAN)
- move SAN filtering out of isNodeCert
- handle private instance IP
- add logging around CSR approvals
> Fix node server cert validation

- Gopkg.lock
- cmd/gke-exec-auth-plugin/BUILD
- cmd/gke-exec-auth-plugin/cache.go
- cmd/gke-exec-auth-plugin/main.go
- cmd/gke-exec-auth-plugin/request.go
- cmd/gke-exec-auth-plugin/tpm.go
- cmd/gke-exec-auth-plugin/tpm_test.go
- vendor/github.com/awly/tpmtls/tpmkey/BUILD
- vendor/github.com/awly/tpmtls/tpmkey/tpmkey.go
- vendor/github.com/google/go-tpm/LICENSE
- vendor/github.com/google/go-tpm/tpm2/BUILD
- vendor/github.com/google/go-tpm/tpm2/README.md
- vendor/github.com/google/go-tpm/tpm2/constants.go
- vendor/github.com/google/go-tpm/tpm2/structures.go
- vendor/github.com/google/go-tpm/tpm2/tpm2.go
- vendor/github.com/google/go-tpm/tpmutil/BUILD
- vendor/github.com/google/go-tpm/tpmutil/encoding.go
- vendor/github.com/google/go-tpm/tpmutil/run.go
- vendor/github.com/google/go-tpm/tpmutil/structures.go
- vendor/k8s.io/client-go/pkg/apis/clientauthentication/types.go
- vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1/types.go
- vendor/k8s.io/client-go/util/certificate/csr/BUILD
- vendor/k8s.io/client-go/util/certificate/csr/csr.go
TPM mode bootstraps TLS key/cert using k8s CSR endpoint with TPM
attestation. The key/cert are cached returned instead of a token.
Note: some parts of the implementation are stubbed out temporarily for
testing.
> Add TPM mode to exec auth plugin

- cmd/gke-exec-auth-plugin/BUILD
- cmd/gke-exec-auth-plugin/cache.go
- cmd/gke-exec-auth-plugin/main.go
- cmd/gke-exec-auth-plugin/request.go
- cmd/gke-exec-auth-plugin/request_test.go
1. rotate when cert is >1d old
2. rotate when cert expires in <1hr
3. if rotation fails, use old cert if still valid
4. if TPM attestation fails, use old bootstrap flow
> Make exec plugin more robust

- cmd/gke-certificates-controller/app/gke_certificates_controller.go
- tools/env.sh
This should cut down ~400ms CSR updates due to shared quota
> Use dedicated clients for informer/approver/signer

- cmd/gke-exec-auth-plugin/cloudbuild.yaml
Builds, tests and pushes to GCS in a versioned directory. This won't
trigger rebuilds on commit (yet).
> Add GCB config for gke-exec-auth-plugin

- cmd/gcp-controller-manager/app/BUILD
- cmd/gcp-controller-manager/app/ca_cache.go
- cmd/gcp-controller-manager/app/ca_cache_test.go
- cmd/gcp-controller-manager/app/gke_approver.go
Root CA lives at a well-known URL. Implement a cache in front of it and
refresh every hour.
Check EK certs signature as well as CA CRLs.
> Check EK cert against root CA

- cmd/gke-exec-auth-plugin/cache.go
- tools/env.sh
This was different from approved design:
- kubelet caches for 1h in memory
- exec plugin caches for 10 days on disk
- certs issued for 1yr
> Rotate kubelet certs after 10 days

- cmd/gcp-controller-manager/OWNERS
> switch owners and reviewers for gcp-controller-manager

- cmd/gcp-controller-manager/app/BUILD
- cmd/gcp-controller-manager/app/controller.go
- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
- cmd/gcp-controller-manager/app/gke_signer.go
- cmd/gcp-controller-manager/app/gke_signer_test.go
- cmd/gcp-controller-manager/app/loops.go
- cmd/gcp-controller-manager/app/options.go
Enables us to start individual controllers. This is required to start only the annotator in GCE.
@kawych
> Refactor gcp-controller-manager startup

- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
- cmd/gcp-controller-manager/app/loops.go
- cmd/gcp-controller-manager/app/node_annotater.go
- cmd/gcp-controller-manager/app/options.go
- cmd/gke-exec-auth-plugin/cache.go
- pkg/nodeidentity/id.go
Fix a few bugs found along:
- CN check didn't trim `system:node:` prefix correctly
- `Zone` in VM identity in AIK was full URL instead of just name
- VM identity in AIK failed to parse because asn1 doesn't understand uint64
- exec plugin would create new CSR on each failed run
> Enable node pool check

- cmd/gcp-controller-manager/app/node_annotater.go
- cmd/gcp-controller-manager/app/node_annotater_test.go
> only reconcile labels when kube-labels instance metadata is present

- Gopkg.lock
- cmd/gcp-controller-manager/app/BUILD
- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
Any GCE API call failure should cause a retry instead of denial of CSRs.
Otherwise kubelets get stuck in CSR retry loop, re-using denied CSR
objects forever.
> Retry CSR failing due to transient errors

- BUILD
- cmd/gcp-controller-manager/app/BUILD
The build wasn't actually broken.
This probably worked because test's dependencies are merged with package
dependencies when package name matches.
Clean it up and I'll add a presubmit check using gazelle-diff
separately. Existing presubmit will catch failing build/test.
> Re-run gazelle and add gazelle-diff command for presubmit

- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
Cert rotation is not enabled in GKE and we will use a TPM-attested
bootstrap for rotation in the future.
> Remove self client cert approver

- cmd/gke-exec-auth-plugin/request.go
Signed-off-by: mooncake <xcoder@tenxcloud.com>
Fix typos: direcly -> directly
> Fix typos: direcly -> directly

- WORKSPACE
- cmd/gcp-controller-manager/app/BUILD
- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
Before approving a client certificate request from a node, ensure any existing Node API object still matches information from metadata, and isn't a vestigial Node object that should be deleted before giving the new one API credentials
Best reviewed split without whitespace: https://github.com/kubernetes/cloud-provider-gcp/pull/63/files?utf8=%E2%9C%93&diff=split&w=1
> ensure Node matches metadata before approving CSRs

- cmd/gcp-controller-manager/app/controller.go
the defaults of 5/10 are not appropriate for a critical-path controller
> bump qps/burst defaults

- cmd/gke-exec-auth-plugin/BUILD
- cmd/gke-exec-auth-plugin/alt_token_source.go
- cmd/gke-exec-auth-plugin/main.go
- vendor/modules.txt
alt_token_source.go is copied and trimmed from the gce cloud provider
which cuts out 25M in binary size.
> add an alt token source mode to the exec plugin

- cmd/gcp-controller-manager/app/BUILD
- cmd/gcp-controller-manager/app/controller.go
- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
- cmd/gcp-controller-manager/app/gke_signer.go
- cmd/gcp-controller-manager/app/metrics.go
- cmd/gcp-controller-manager/app/node_annotater.go
Moved metrics from `gke_approver.go` to new `metrics.go`.
Fixed a bunch of go-lint errors. 
Cleanup in anticipation of plumbing additional metrics
> Moved pantheon metrics to their own file and fixed various go-lint errors

- WORKSPACE
- cmd/gcp-controller-manager/app/BUILD
- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
- cmd/gcp-controller-manager/app/options.go
Instances are not guaranteed to be in cluster master's zone:
- in regional clusters
- in regional NodePools
Also handle the case of regional NodePools when checking Node
membership.
Add tests to cover some common cases.
This fix only applies to vTPM attestation validator.
> Use cluster's location when fetching from GKE API

- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/gke_approver_test.go
- cmd/gcp-controller-manager/app/options.go
- cmd/gcp-controller-manager/app/options_test.go
Startup was failing because of option parsing code assuming cluster-location metadata being a zone.
CSR approval was failing because we were fetching cluster object from API by zone instead of location.
> Fix startup and CSRs for regional clusters

- cmd/gke-exec-auth-plugin/BUILD
- cmd/gke-exec-auth-plugin/main.go
- go.mod
- go.sum
- vendor/github.com/gofrs/flock/.gitignore
- vendor/github.com/gofrs/flock/.travis.yml
- vendor/github.com/gofrs/flock/BUILD
- vendor/github.com/gofrs/flock/LICENSE
- vendor/github.com/gofrs/flock/README.md
- vendor/github.com/gofrs/flock/appveyor.yml
- vendor/github.com/gofrs/flock/flock.go
- vendor/github.com/gofrs/flock/flock_unix.go
- vendor/github.com/gofrs/flock/flock_winapi.go
- vendor/github.com/gofrs/flock/flock_windows.go
- vendor/modules.txt
- Added [github.com/gofrs/flock](https://github.com/gofrs/flock) dependency
- Used flock to create a filesystem lock wrapping `gke-exec-auth-plugin/main.go`
Tested locally with a `time.Sleep` and two parallel invocations of `gke-exec-auth-plugin --mode=foo` and it works great! :smiley:
> Filesystem lock for gke-exec-auth-plugin

- cmd/gke-exec-auth-plugin/main.go
Since the binaries will be run in their own containers `os.TempDir()` likely means different things on disk in each container so the lock will not work. Moved the lockfile dir to the cache dir which is a folder mounted/shared between containers.
> Moved lockfile from os's tmp to cache dir.

- cmd/gcp-controller-manager/app/controller.go
- cmd/gcp-controller-manager/app/gke_approver.go
- cmd/gcp-controller-manager/app/loops.go
- cmd/gcp-controller-manager/app/options.go
When TPM-backed bootstrap is enabled in cluster, prevent old bootstrap
flow to ensure only compliant nodes are allowed.
> Add a flag to disable legacy kubelet bootstrap

- cmd/gke-exec-auth-plugin/BUILD
By default the binary dynamically links to libraries such as `glibc`. This would prevent `gke-exec-auth-plugin` from running in containers where this library is not present.
The build rule `pure = "on"` builds the binary with complete static linking of required libraries.
> Disabled dynamic linking of gke-exec-auth-plugin binary.

- cmd/gcp-controller-manager/gcp_config.go
- cmd/gcp-controller-manager/main.go
Carrying over from https://github.com/kubernetes/kubernetes/blob/8765fa2e48974e005ad16e65cb5c3acf5acff17b/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L421-L429
Need this to access other zones, currently hitting
```
node_annotater.go:201] Sync [node-name] failed with: googleapi: Error 400: Invalid value for field 'zone': '****'. Unknown zone., invalid
```
/assign @awly
> Allow override GCE Endpoint in gcp-controller-manager

- cmd/gcp-controller-manager/main.go
Adding flag.FlagSet to pflag.FlagSet should only be done after we add
everything to the stdlib FlagSet.
Any flags we add afterwards don't reflect in pflag's FlagSet.
This makes the process fail at startup when any klog-related flags are
passed in.
> Fix klog flag set

- WORKSPACE
The error was:
Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped,
and the mandatory parameter 'ctx' of cc_common.configure_features is missing.
Please add 'ctx' as a named parameter.
See https://github.com/bazelbuild/bazel/issues/7793 for details.
> Update rules_go to resolve bazel compatibility.

- tools/merge_licenses.sh
This commit modifies merge_licenses.sh to include the top-level
LICENSE file for this repository, as well as the licenses of all
vendored libraries.
> merge_licenses.sh: Include own LICENSE

- cmd/gcp-controller-manager/node_annotator.go
The label "addon.gke.io/node-local-dns-ds-ready" is used to select nodes that can run the node-local-dns daemonset.
> Include node-local-dns label in node_annotator.go

- WORKSPACE
These changes fix a build error currently at HEAD and are also needed to prepare for building gke-exec-auth-plugin for Windows.
Updates:
- go toolchain to 1.13
- rules_go to v0.20.0
- gazelle to v0.19.0
- rules_docker to v0.11.0
io_bazel_rules_go needs updating for bazelbuild/rules_go#2118 (bazelbuild/rules_go#1240).
bazel_gazelle and go_sdk need updating for compatibility with vendor/ targets that will be updated.
rules_docker needs updating to eliminate failures when running `bazel build ...` at HEAD. The corresponding update to the go toolchain is needed to completely eliminate the failures. For some more details see this [gist](https://gist.github.com/pjh/3e409e8d73dad63782b333c6535696de).
With these changes and a `gcloud auth login`, running `bazel build ...` to build the entire …
> Update numerous toolchain components.

- cmd/gke-exec-auth-plugin/request.go
- cmd/gke-exec-auth-plugin/request_test.go
`caFilePath` is hard-coded to a Linux path. This PR lets this path be overridden by a kube-env key, which will then be set by shielded Windows kubernetes nodes ([k/k changes in progress](https://github.com/kubernetes/kubernetes/compare/master...pjh:gce-shielded-windows?expand=1)). `gke-exec-auth-plugin.exe` then runs correctly.
This change is a noop for existing plugin users. The chosen kube-env key for specifying the path is [not used anywhere in k/k](https://github.com/kubernetes/kubernetes/search?q=%22CA_FILE_PATH%22&unscoped_q=%22CA_FILE_PATH%22).
There are alternative mechanisms we could use for setting this path for Windows: making it a flag, or making it constant with different Windows vs. Linux values at build time. This path is already only used `kubeEnvToConfig()` though so …
> Let CA file path be set via kube-env to enable Windows paths.

- cmd/gcp-controller-manager/main.go
They do the long-running watch requests that get interrupted by timeouts
in kubeconfig.
/assign @mikedanese
> Don't set a timeout on informers in gcp-controller-manager

- WORKSPACE
Latest always moves which breaks the build since image sha256 changes.
This fixed tag (matches commit hash) should remain static.
/assign @mikedanese @sambdavidson
> Pin distroless/static image to a tag instead of latest

- cmd/gcp-controller-manager/BUILD
- cmd/gcp-controller-manager/healthz/BUILD
- cmd/gcp-controller-manager/healthz/healthz.go
- cmd/gcp-controller-manager/healthz/healthz_test.go
- cmd/gcp-controller-manager/main.go
Behind the scenes it checks whether informer caches are synced and
whether leader lease hasn't expired after election.
> Add /healthz endpoint to gcp-controller-manager

- cluster/gce/gci/configure.sh
- cluster/gce/util.sh
- release/BUILD
Creates the missing sha files referenced in #145.
We now create sha512 for the generated tgz files.
Switched the relevant checks from sha1 to sha512.
This is *not* fixing the legacy/out of repo sha1 generation.
So NPD, node etc are still on sha1.
> Fix missing sha reference in cluster-up.

- cluster/addons/cloud-controller-manager/cloud-node-controller-role.yaml
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/configure-kubeapiserver.sh
- cluster/gce/manifests/cloud-controller-manager.manifest
- defs/container.bzl
- deploy/cloud-controller-manager.manifest
- deploy/cloud-node-controller-role.yaml
- release/BUILD
- tools/version.sh
- tools/workspace-status.sh
CCM image was set to a blaize repository instead of k8s.gcr.io.
CCM image had unneeded path info in it.
CCM image was tag with 'image'.
Added a script to determine the 'dirty' tag for one off builds.
Assuming a hard coded base version for now.
However it is a 1 line change to pick up version from a git tag.
Fixed issue in manifest based on us using distroless base image.
Fixed config to actually write out the log file.
Fixed manifests to use external cloud provider when appropriate.
> Fix CCM image.

- cluster/common.sh
Like the rest of the code in kube-up, verify-kube-binaries
should not look for binaries based on the current working
directory. Instead, it should use $KUBE_ROOT.
> verify-kube-binaries uses relative path instead of fixed

- cluster/gce/util.sh
- test/boskos.sh
This did not cause issues in the past because the current e2e script sets `$CLOUDSDK_CORE_PROJECT` which the gcloud utils use. However, `$PROJECT` should be supported and preferred. Before this fix, if the user sets `$PROJECT` but has a different default project, the bucket gets created in the wrong project and the created VMs cannot read from that bucket due to permission issues.
Related to this issue, and included in this PR: the _only_ place (outside of the windows README) that `$CLOUDSDK_CORE_PROJECT` is even referenced is in the test/boskos.sh script. Updated to make it use `$PROJECT` as well to conform with the norm.
Tested by setting just `$PROJECT` and just `$CLOUDSDK_CORE_PROJECT`.
> Create the bucket for tars based on $PROJECT

- cluster/gce/util.sh
In a fresh GCP project, kube-up.sh will fail on two runs before succeeding. This is because it copies two files to staging during its run. When the file 1 is copied to the bucket, we hit this ACL-setting line which fails for weird bucket permission errors. The next run, kube-up discovers that file 1 is already in the bucket and doesn't call copy-to-staging, proceeding instead to copying file 2 to staging. The same error occurs. On the third run, both files are determined to be in the bucket and available and so the script proceeds without incident and completes a successful run. With this addition of || true, multiple runs are not necessary (it stops -e from killing the process).
**I would like to weigh this fix against removing the ACL change entirely, as it doesn't seem to be necessary. …
> Ignore meaningless failures when setting bucket ACLs during kube-up.sh

- WORKSPACE
Fixes error encountered when running `bazel build //release:release-tars` on current master.
`
ERROR: /usr/local/google/home/dresser/.cache/bazel/_bazel_dresser/944c284ce0faecea697971732fd904d3/external/io_bazel_rules_docker/container/BUILD:85:11: no such package '@bazel_tools//third_party/py/gflags': BUILD file not found in directory 'third_party/py/gflags' of external repository @bazel_tools. Add a BUILD file to a directory to mark it as a package. and referenced by '@io_bazel_rules_docker//container:build_tar_lib'
`
Updates to latest version based on: https://github.com/bazelbuild/rules_docker#setup
> Updated rules_docker to latest to fix build error

- cmd/gcp-controller-manager/node_annotator.go
- cmd/gcp-controller-manager/node_annotator_test.go
- cmd/gcp-controller-manager/node_syncer.go
Current node annotator requeues node sync action on failure constantly without exponential backoff.
Modify the behavior to correctly follow the exponential backoff and impose retry limit for failures.
> Make node annotator failure retry correctly follow queue rate limiter

- cmd/gcp-controller-manager/csr_approver.go
- cmd/gcp-controller-manager/csr_approver_test.go
- cmd/gcp-controller-manager/csr_signer.go
- cmd/gcp-controller-manager/csr_signer_test.go
CSR signer names, a mechanism for having multiple CSR signers coexisting in the same cluster, have landed in Kubernetes 1.18.  To let auxiliary approvers and signers coexist with the default signer, it needs to be updated to only handle CSRs that are addressed to it.
This commit:
* Updates the approver to only act on CSRs addressed to `kubernetes.io/kube-apiserver-client-kubelet` and `kubernetes.io/kubelet-serving`.
* Updates the signer to only act on CSRs addressed to `kubernetes.io/kube-apiserver-client`, `kubernetes.io/kube-apiserver-client-kubelet`, `kubernetes.io/kubelet-serving`, and `kubernetes.io/legacy-unknown`.
This should preserve all existing usecases, including that of people manually approving CSRs with kubectl and then having them be signed by the default signer.
> CSR Approver/Signer: Only handle CSRs meant for the default signer

- OWNERS
Ref: kubernetes/org#2076
As a part of cleaning up inactive members (who haven't been active since
beginning of 2019) from OWNERS files, this commit moves nicksardo to
emeritus_approvers section.
cc @nicksardo @mrbobbytables 
/kind cleanup
/assign @cheftako
> OWNERS: move nicksardo to emeritus_approvers

- cmd/gke-exec-auth-plugin/main.go
Because we were not calling klog.InitFlags, klog was logging to /tmp directory.
> Add klog.InitFlags to correctly handle klog flags.

- cluster/gce/windows/k8s-node-setup.psm1
- cluster/gce/windows/smoke-test.sh
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
As part of the efforts described in this Issue: https://github.com/kubernetes/k8s.io/issues/1525 we are trying to move away from `gcp project gke-release`
Also the pause image was release with windows support as we can see in the merged or in k/k https://github.com/kubernetes/kubernetes/pull/98205
/assign @spiffxp @saad-ali
> test: update pause-win image to the new one k8s.gcr.io/pause:3.4.1

- cmd/gcp-controller-manager/csr_approver.go
- cmd/gcp-controller-manager/csr_approver_test.go
The gcp-cloud-provider auto-approves CSR requests for serving certificates using logic at https://github.com/kubernetes/cloud-provider-gcp/blob/16a329f8c7133b72f4950aba624b6e3b3c24a66c/cmd/gcp-controller-manager/csr_approver.go#L347-L389
That approver verifies the IP address SANs in the CSR are actually associated with the node record in metadata. It does not verify DNS names in the CSR at all.
This would allow anyone with node credentials to request/obtain a serving certificate signed by the cluster CA valid for any DNS name, including DNS names associated with other nodes.
Because the kube-apiserver runs configured with --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname, and GCP nodes report InternalIP and ExternalIP addresses, the kube-apiserver will use IP info to …
> Add DNS csr verification for gcp-controller-manager

- cluster/OWNERS
ref: https://github.com/kubernetes/org/issues/2456
Move gmarek and jingax10 to emeritus
/assign @cheftako
> cluster: Remove inactive members from OWNERS

- cmd/gcp-controller-manager/csr_approver.go
- cmd/gcp-controller-manager/csr_approver_test.go
With the following query:
```
resource.type="container"
resource.labels.cluster_name="staging2-xpn-windows-2021-02-26-1f192"
resource.labels.container_name="gcp-controller-manager"
```
The code failed with error message `deny CSR "csr-srd6l": DNSName in CSR ("gke-staging2-xpn-windows--test-win-np-dcf30bf7-22kw") doesn't match default DNS format on instance "gke-staging2-xpn-windows--test-win-np-dcf30bf7-22kw"`
> Bugfix for DNS validation doesn't work for Windows

- README.md
- WORKSPACE
- release/BUILD
This PR is intended to add the ability to build Windows nodes while using the `--platforms=@io_bazel_rules_go//go/toolchain:windows_amd64` option in Bazel, e.g., `bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //release:release-tars`. This PR does not handle deployment of Windows nodes, only building.
> Windows crossbuild support

- cmd/gcp-controller-manager/gcp_config.go
This sets the user agent field for all the clients of GCP APIs used by the GCP controller manager.
> Set user agent for GCE and GKE API clients

- tools/verify-all.sh
Add verify-all.sh to cloud-provider-gcp.
Plan to add this script as presubmits. If we plan to add any further checking to presubmits, it would be easier by adding to verify-all.sh
> Add verify-all.sh

- tools/coverage/golang_coverage.sh
Script will be used to generate code coverage for gke-exec-auth-plugin
and gcp-controller-manager
> Add Go code coverage script

- cluster/gce/gci/configure-helper.sh
This PR removes the ability for `start-cloud-controller-manager` to add `--terminated-pod-gc-threshold`, `--experimental-cluster-signing-duration`, and `--horizontal-pod-autoscaler-use-rest-clients` as options for the CCM, since all three only apply to the KCM and will prevent the CCM from starting if passed.
The full list of supported options, as seen from `cloud-controller-manager --help`, can be seen [here](https://gist.github.com/DangerOnTheRanger/a3af8ebb420210db9ac9e6a56661da56).
> Remove invalid options from CCM manifest

- cmd/gcp-controller-manager/BUILD
- cmd/gcp-controller-manager/main.go
The component-base package already calls klog.InitFlags in an init() function (whhhyyyyyyy???).  We were transitively including the offending package.  Make the dependency explicit, and remove our now-redundant call to InitFlag.
> gcp-controller-manager: Fix startup panic

- tools/verify-golint.sh
https://github.com/kubernetes/cloud-provider-gcp/pull/216 just failed because `go get` was updating go.mod, which then causes the check that vendor/modules.txt fails: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-gcp/216/cloud-provider-gcp-verify-all/1391845103726759936/build-log.txt
I've fixed this by instead using `go install -mod readonly`
> do a readonly install of golint for tools/verify-golint.sh

- cluster/gce/config-common.sh
This PR increases the minimum returned VM model from an `n1-standard-1` to `n1-standard-2`, as there are resource limit issues with the 1vCPU model with `kubetest2`.
* Resource usage with [`n1-standard-2`](https://github.com/kubernetes/cloud-provider-gcp/pull/216#issuecomment-837469430)
* Resource usage with [`n1-standard-1`](https://gist.github.com/DangerOnTheRanger/6ca3d0e16f901f595732d3fd952bf684)
> Use at minimum n1-standard-2 in cluster/gce/config-common.sh

- cluster/gce/gci/BUILD
- go.mod
- go.sum
- providers/go.mod
- vendor/modules.txt
To reduce dependency update when vendor in //providers from K/K,  sync //providers dependencies versions.
> Sync //providers dependencies version with k/k

- cluster/gce/gci/configure-helper.sh
get-credentials needs to be passed in args to make gcp-auth-provider working
> Update gcp auth provider config

- tools/workspace-status.sh
1. We need to allow image overrides for testing. IMAGE_TAG shouldn't be overriden if set.
2. `+` characters are not allowed in image tags. In k8s, we swap these with underscores.
Tested with:
```
IMAGE_REPO=mikedanese-k8s IMAGE_TAG=latest bazel run //cmd/gcp-controller-manager:publish
```
and
```
IMAGE_REPO=mikedanese-k8s bazel run //cmd/gcp-controller-manager:publish
```
> fix image tag derivation

- cmd/auth-provider-gcp/provider/provider.go
- cmd/auth-provider-gcp/provider/provider_test.go
This PR fixes #226 by setting `response.CacheKeyType`  on the credential provider and checking for its presence/correctly set value in the unit test suite.
> Set CacheKeyType on credential provider response

- cmd/gcp-controller-manager/loops.go
- cmd/gcp-controller-manager/node_syncer.go
- cmd/gcp-controller-manager/node_syncer_test.go
In a regional cluster, the cluster location is the region. syncNode is zonal, so that it will fail. Add nodeZones to get node's zone via k8s clientset and store the result in a map.
> Use node's (not cluster's) location in syncNode to support Direct-Path in regional clusters

- cluster/common.sh
- cluster/gce/gci/configure-helper.sh
- cluster/gce/gci/configure.sh
- cluster/gce/upgrade.sh
- cluster/gce/util.sh
- cluster/get-kube-binaries.sh
- cluster/get-kube.sh
- defs/repo_rules.bzl
The only time a kubernetes GCS bucket name should be showing up in a
hardcoded URI is if gsutil is being used (e.g. gsutil cp gs://foo/bar .)
Otherwise, for tools like curl or wget, dl.k8s.io is much nicer for us
as a project, since we can transparently change where that redirects to
without having to change code everywhere
These changes will mean very few changes will be necessary to
accommodate a gs://kubernetes-release -> gs://k8s-release migration
equivalent of the CI migration we're going through right now
These changes also address the gs://kubernetes-release-dev references
currently used by this repo (ref:
https://github.com/kubernetes/k8s.io/issues/2318)
For reference, some similar PRs:
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/399
- …
> use dl.k8s.io where possible

- cmd/gke-gcloud-auth-plugin/BUILD
- pkg/csrapproval/BUILD
- pkg/csrapproval/csrapproval.go
update-approval requires the csr name in a param,
and csr.Condition.Status must be set.
> pkg/csrapproval: fix setting required fields

- WORKSPACE
- go.mod
- providers/go.mod
- tools/verify-golint.sh
We should port this back to our release-1.21 branch after this merges.
> bump to go1.16

- cmd/gke-gcloud-auth-plugin/main.go
Update gke-gcloud-auth-plugin to add a flag to return application default credentials and skip the gcloud command
> Update gke-gcloud-auth-plugin to add a flag to return application default credentials and skip the gcloud command

- providers/gce/gce.go
- providers/gce/gce_instances.go
- providers/gce/gce_instances_test.go
These changes populate the Node object with the IPv6 address as well as the IPv6 podCIDR. This is done only for clusters with stackType as IPV4_IPV6. This patch handles both the internal and external IPv6 addresses.
> Changes to support IPv6 addresses on nodes

- cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml
As part of the efforts described in this Issue https://github.com/kubernetes/k8s.io/issues/1525
moving out from `gcr.io/gke-release` to `k8s.gcr.io` community registry
This image was changed to an equivalent in k/k per this PR https://github.com/kubernetes/kubernetes/pull/100294
Applying the same changes here.
/assign @spiffxp @bowei @BenTheElder
> replace gcr.io/gke-release to use the community registry for nvidia-gpu-device-plugin

- cluster/gce/gci/node.yaml
Duplicate https://github.com/kubernetes/kubernetes/pull/103376 over to this repo.
I think this is the right thing to do in order to ensure this change stays in GKE?
/assign @jpbetz
> Drop end of sunrpc port range to avoid port conflicts

- cmd/gcp-controller-manager/node_csr_approver_test.go
- go.mod
- go.sum
- pkg/apis/firewall/BUILD
- vendor/github.com/google/go-tpm/tpm2/constants.go
- vendor/github.com/google/go-tpm/tpm2/kdf.go
- vendor/github.com/google/go-tpm/tpm2/structures.go
- vendor/github.com/google/go-tpm/tpm2/tpm2.go
- vendor/github.com/google/go-tpm/tpmutil/BUILD
- vendor/github.com/google/go-tpm/tpmutil/poll_unix.go
- vendor/github.com/google/go-tpm/tpmutil/structures.go
- vendor/modules.txt
Version 0.2.0 of go-tpm library did not support building for linux_arm64.  See error below.
```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64 //cmd/gke-exec-auth-plugin:gke-exec-auth-plugin 
workspace/vendor/github.com/google/go-tpm/tpmutil/poll_unix.go:28:33: undefined: syscall.SYS_POLL
Target //cmd/gke-exec-auth-plugin:gke-exec-auth-plugin failed to build
INFO: Elapsed time: 0.922s, Critical Path: 0.25s
INFO: 15 processes: 10 internal, 5 linux-sandbox.
FAILED: Build did NOT complete successfully
```
The failure above happens because v0.2.0 of the go-tpm library used syscall.SYS_POLL which is not supported in arm64 architecture. To workaround this golang has implemented a shim for poll on arm64 in https://go-review.googlesource.com/c/sys/+/24062/. This issue has …
> Update go-tpm version to v0.3.2 that supports arm64

- providers/gce/gce_instances.go
- providers/gce/gce_instances_test.go
A recent change #268 introduced dual stack support, but it also began to require Google Cloud Compute Aplha API access. Unfortunately by default projects don't have this access, and therefore the CCM fails with:
> googleapi: Error 403: Required 'Alpha Access' permission for 'Compute API', forbidden
This commit starts using Alpha API only for dual stack deployments, where it's really required. For all other cases we will continue to use GA API.
Fixes: #281
> Use Alpha Compute API only in case of dual stack

- cmd/gcp-controller-manager/BUILD
- cmd/gcp-controller-manager/node_annotator.go
- cmd/gcp-controller-manager/node_annotator_test.go
This change adds a 3-way merge logic for node taints to merge taints
present in the instance metadata with the taints present on the node.
This is similar to the 3-way merge logic that we have for labels today.
The reason we are adding this is to have a consistent way to merge user
provided taints with existing K8s specific node taints similar to what
we do for labels today.
> Add 3-way merge for node taints

- providers/gce/gce.go
After recent change in Google Cloud SDK we get malformed URLs because they don't have "projects/" inside.
This happens because basePath constant there lost "projects/" suffix.
This commit updates the created BasePath on our side to fix the issue.
Fixes: #286
> Fix service BasePath 

- cluster/gce/gci/configure-helper.sh
Fixes #292. This PR was tested by bringing up a cluster via `kube-up` while having `KUBE_ENABLE_CREDENTIAL_SIDECAR=true` to ensure the feature gate codepath was executed in `configure-helper`.
> Log feature gates that did not pass through the GCP feature gate filter

- cmd/gke-exec-auth-plugin/cache.go
- cmd/gke-exec-auth-plugin/tpm.go
These error logs cause a fair bit of confusion when we debug issues with
the gke-exec-auth-plugin. I only switched those errors to warnings that
have a fallback.
> Switch the errors to warnings that are expected on first run.

- cmd/gcp-controller-manager/main.go
Support for endpoints lock for leaderelection is removed in K8s 1.24 with kubernetes/kubernetes#106852.
More details about the motivation to switch to leases - ref kubernetes/kubernetes#80289.
To preserve the backward compatibility, resource lock for migration purposes (endpointsleases) should be used when switching from the legacy resource locks (endpoints).
`cloud-provider-gcp` is currently using endpoints. As the first step, this PR adapts endpointsleases.
Once this is merged, we can migrate to leases.
Fixes - #309
> Migrate `cloud-provider-gcp` resourcelock to `endpointsleases`

- README.md
- crd/client/gcpfirewall/clientset/versioned/BUILD
- crd/client/gcpfirewall/clientset/versioned/fake/BUILD
- crd/client/gcpfirewall/clientset/versioned/scheme/BUILD
- crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1alpha1/BUILD
- crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1alpha1/fake/BUILD
- crd/client/gcpfirewall/informers/externalversions/BUILD
- crd/client/gcpfirewall/informers/externalversions/gcpfirewall/BUILD
- crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1alpha1/BUILD
- crd/client/gcpfirewall/informers/externalversions/internalinterfaces/BUILD
- crd/client/gcpfirewall/listers/gcpfirewall/v1alpha1/BUILD
- tools/lib/util.sh
- tools/update_vendor.sh
- tools/verify-all.sh
- tools/verify-vendor.sh
Add go mod tidy into update-vendor
Add verify-vendor.sh and include it into presubmit checking.
Add go version print out when run pre-submit checking.
Close #299 
Close #297 
Here is an sample run of vendor verification in presubmit check: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/cloud-provider-gcp/301/cloud-provider-gcp-verify-all/1470500659454283776
> Add verify-vendor

- cmd/gke-exec-auth-plugin/BUILD
- cmd/gke-exec-auth-plugin/main.go
- go.sum
client exec apiVersion v1alpha1 support is removed in 1.24 https://github.com/kubernetes/kubernetes/pull/108616. For gke-exec-auth-plugin to work in 1.24+ clusters we need to switch to using v1beta1 apis.
> Update clientauthentication apis from v1alpha1 to v1beta1 in gke-exec-auth-plugin

- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
In case of dual stack VMs, the IPv6 addresses are present either under the networkInterface.Ipv6Address or the Ipv6AccessConfig.ExternalIpv6 fields. This function was not reading these.
> Handle IPv6 addresses on network interfaces in validateNodeServerCert

- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
Comparing the string form of IPv6 address could be incorrect depending on how the IPv6 address was normalized. Instead, we change the logic to compare the net.IP values. Also fixed the log message to print out the instance IP addresses.
> Fix bug in comparing IPv6 addresses on the instance

- pkg/clientauthplugin/README.md
- pkg/clientauthplugin/gcp/BUILD
- pkg/clientauthplugin/gcp/gcp.go
- pkg/clientauthplugin/gcp/gcp_test.go
Add gcp.go from client-go to cloud-provider-gcp as that file is being deprecated from client-go.
If users do not want to use an additional binary (gke-gcloud-auth-plugin),
then we they can reference and build this library in to their custom k8s
clients to provide the same functionality. This use case becomes
necessary if customers are unwilling to add additional binaries on their
system to avoid remote code execution attacks.
> Add gcp.go from client-go to cloud-provider-gcp 

- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gke-exec-auth-plugin/request.go
- pkg/csrapproval/csrapproval.go
/cc @mikedanese 
1.26 nodes will start requesting these for non-RSA keys
> Tolerate CSRs without encipherment key usage

- cluster/addons/cloud-controller-manager/cloud-node-controller-role.yaml
- cluster/gce/gci/configure-helper.sh
- cluster/gce/manifests/cloud-controller-manager.manifest
- cmd/cloud-controller-manager/nodeipamcontroller.go
- pkg/controller/nodeipam/BUILD
- pkg/controller/nodeipam/node_ipam_controller.go
Also, fix liveness probe in deployment manifest and add support for accessing '/metrics' endpoint
/assign @tosi3k
> Add support for nodeipam metrics

- cmd/gcp-controller-manager/BUILD
- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
After node's preemption, pods bound to the deleted node may not finish termination and will be in failed phase stays in the pod list. Especially in preemptible VMs, graceful shutdown (30 seconds) can meet the requirement to clean pods on time.
@bobbypage and I worked on cleaning pods bound to the old node when the new node is registered. Our code checks nodes with obsolete GCE instance id, list all pods bound to it, and delete these pods.
> Delete nodes if the GCE instance id changes and pods bound to the deleted node

- pkg/clientauthplugin/gcp/gcp.go
This was copied over and isn't correct. This is the new location for this plugin.
> remove deprecation warning in new clientauthplugin package

- cmd/gcp-controller-manager/loops.go
- cmd/gcp-controller-manager/main.go
- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
To prevent operations that delete pods bound to the old node do not cause any regression in cluster creation, we added cleanPreemptibles flag to toggle the cleaning process.
> Added clearStalePodsOnNodeRegistration flag to guard removal of pods bound to preemptible node

- crd/apis/network/v1/annotations.go
- crd/apis/network/v1/annotations_test.go
This annotation is used to identify the interfaces information on a node. The corresponding struct consists of network and ipAddress information of the interface.
> Define north-interface annotation.

- providers/gce/BUILD
- providers/gce/gce_subnetworks.go
1. Add gce_subnetworks.go for building the library to fetch the subnetworks info. We need the subnetwork info when we create the network manager controller.
2. Add metrics to observe the call and checking time out, since we need to follow other library's style under gce folder
> Changes for fetching the subnetworks.

- cmd/gcp-controller-manager/BUILD
- cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go
- cmd/gcp-controller-manager/kubelet_readonly_csr_approver_test.go
Since CSR request does not contain namespace for the pod. We could not use get pod. it will report namespace empty error. switch to list. list function will list all namespaces pods if namespace value is empty
Tested:
Unit test
> Get namespace from service account

- providers/gce/gce_instances.go
- providers/gce/gce_instances_test.go
Introduce InstanceByProviderID method to fetch gce compute.Instance by provider ID. Removed the previously introduced
NodeNetworkInterfacesByProviderID as it is obsolete now.
> Add a utility method to fetch compute instance

- crd/apis/network/v1/annotations.go
This annotation key/value pair is consumed in the multi-networking datapath components.
Signed-off-by: Bolun Zhao <blzhao@google.com>
> Add EnableMulticastAnnotationKey and value

- crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparams.go
- crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
- crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparams.go
- crd/client/network/clientset/versioned/typed/network/v1/network_client.go
- crd/client/network/informers/externalversions/generic.go
- crd/client/network/informers/externalversions/network/v1/gkenetworkparams.go
- crd/client/network/informers/externalversions/network/v1/interface.go
- crd/client/network/listers/network/v1/gkenetworkparams.go
- crd/hack/update-codegen.sh
Updates codegen script to account for incorrect pluralization of GKENetworkParams. It was transforming the resource to GKENetworkParamses. We think this is due to the resource name ending in s, some implicit name change is done in client-gen.
This fix allows the clientset to correctly find GKENetworkParams resources inside the cluster.
> Fix GKENetworkParams pluralization 

- crd/apis/network/v1/gkenetworkparams_types.go
- crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparams.go
- crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
- crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparams.go
- crd/client/network/clientset/versioned/typed/network/v1/network_client.go
- crd/client/network/informers/externalversions/network/v1/gkenetworkparams.go
- crd/client/network/informers/externalversions/network/v1/interface.go
- crd/client/network/listers/network/v1/expansion_generated.go
- crd/client/network/listers/network/v1/gkenetworkparams.go
GKENetworkParams is a cluster wide resource. We shouldn't be asking for namespace in the client.
> Fix GKENetworkParams client asking for namespace. (Resource is cluster wide)

- cmd/gcp-controller-manager/loops.go
https://github.com/kubernetes/cloud-provider-gcp/pull/348/commits changed all worker numbers to 20. But
1. For serviceAccountVerifier, there're only a few thousands or fewer SAs.
2. For nodeSyncer, we'd like more workers to achieve high QPS to HMS, see https://github.com/kubernetes/cloud-provider-gcp/pull/337
> Restore serviceAccountVerifier workers to 3 and nodeSyncer to 30 from 20

- cloudbuild.yaml
Current tag published is always set to `master`and previous one was really weird, use the short sha
Revert the change to publish latest with another build, the digest of the docker images doesn't match, we should be able to push 2 tags for the same image, it seems bazel can do it
https://github.com/bazelbuild/rules_docker/issues/108
@fejta is this something you can guide us or help here?
> Cloudbuild iterations

- deploy/cloud-node-controller-role.yaml
This is needed for the IPAM controller, to patch the node.Spec.PodCIDR
https://github.com/kubernetes/cloud-provider-gcp/blob/b5a04079d4acab62378a522cbb9fc1538e14ad3f/pkg/controller/nodeipam/ipam/adapter.go#L104-L118
/assign @justinsb @andrewsykim @jprzychodzen
> add permissions for patch node to cloud-controller-manager

- cmd/gcp-controller-manager/loops.go
- cmd/gcp-controller-manager/main.go
- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
ListReferrers will list the instanceGroups that an instance is a MEMBER_OF
For the following request:
```
GET https://compute.googleapis.com/compute/v1/projects/p1/zones/us-central1-c/instances/1234/referrers?key=[YOUR_API_KEY] HTTP/1.1
Authorization: Bearer [YOUR_ACCESS_TOKEN]
Accept: application/json
```
We get the following response:
```
{
"kind": "compute#instanceListReferrers",
"id": "projects/p1/zones/us-central1-c/instances/1234/referrers",
"items": [
{
"kind": "compute#reference",
"target": "https://www.googleapis.com/compute/v1/projects/p1/zones/us-central1-c/instances/abcd",
"referenceType": "MEMBER_OF",
"referrer": "https://www.googleapis.com/compute/v1/projects/p1/zones/us-central1-c/instanceGroups/efgh"
}
],
"selfLink": …
```
> Use instance ListReferrers method to check cluster membership.

- pkg/controller/nodeipam/ipam/BUILD
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
This PR includes changes to support pod multi-networking. It updates the annotations and per network IP capacity on the node.
> Update node annotations for multi-networking

- cmd/gcp-controller-manager/node_csr_approver.go
parseInstanceGroupURL return names, location, error but we were assigning the return values as
```
location, igName, err := parseInstanceGroupURL(...)
```
> Fix incorrect return value ordering in validateInstanceGroupHint.

- crd/apis/network/v1/network.go
- crd/apis/network/v1/network_types.go
Existing DefaultNetworkName will be deprecated in favour of this new constant. We plan to support both `pod-network` and `default` values until we come up with a migration plan.
Importing libraries/files should use the new `IsDefaultNetwork` which will return true if network is default instead of directly comparing the constants.
> Introduce DefaultPodNetworkName constant

- deploy/packages/default/manifest.yaml
- e2e/scenarios/kops-simple
Uploading for discussion.
A simple e2e test that tests with a manifest that we provide. Solves the problem that we need to test with a configuration, treating that as part of our distribution (unless we want to test and support everything!).
Example issue: https://github.com/kubernetes/cloud-provider-gcp/pull/393
> e2e: add test scenario to test with kOps

- cluster/addons/pdcsi-driver/pd-csi.yaml
- cluster/gce/manifests/pdcsi-controller.yaml
- cmd/auth-provider-gcp/provider/provider_test.go
This PR will update the uses of deprecating `[k8s.gcr.io](http://k8s.gcr.io/)` registry to `[registry.k8s.io](http://registry.k8s.io/)` prior to the planned April freeze.
Tracking Issue: https://github.com/kubernetes/k8s.io/issues/4738
Search results: https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes/cloud-provider-gcp
> Update registry k8s.gcr.io -> registry.k8s.io

- e2e/add-kubernetes-to-workspace.sh
- e2e/scenarios/kops-simple
We tweak the scenarios and make it easier to run with a go workspace, including building with the latest k/k.
> e2e scenario test: Build with workspace

- e2e/scenarios/kops-simple
If GCP_PROJECT is not explicitly set, fetch the project from boskos.
Also default and create storage buckets to avoid the need for project setup.
> e2e/kops: Get project from boskos

- WORKSPACE
This new version of go-runner is built using 1.19.6 that contains security patches.
> Bump go-runner image version to latest patch version.

- cmd/gcp-controller-manager/BUILD
- defs/container.bzl
Allow gcp-controller-manager to use distoless as the base image instead of go-runner.
> Allow binaries to set the base image.

- cmd/gcp-controller-manager/main.go
Fixes - #309 
Follow-Up after #310
> Migrate `cloud-provider-gcp` resource lock to `leases`

- cmd/gke-gcloud-auth-plugin/cred.go
- cmd/gke-gcloud-auth-plugin/cred_test.go
- cmd/gke-gcloud-auth-plugin/default_credentials_token_provider.go
- cmd/gke-gcloud-auth-plugin/gcloud_edge_cloud_token_provider.go
- cmd/gke-gcloud-auth-plugin/gcloud_token_provider.go
- cmd/gke-gcloud-auth-plugin/token_provider.go
Update the gcloud token provider to use extra project and account args if present. This way when using gcloud the global account and project flags can be passed down to the exec auth plugin. Currently this plugin only allows for using the default account and project on your gcloud.
> Support account and project flags in gke-gcloud-auth-plugin

- crd/apis/gcpfirewall/v1beta1/types.go
- crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall.go
- crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall_client.go
- crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall.go
- crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall_client.go
- crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/gcpfirewall.go
- crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/interface.go
- crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/expansion_generated.go
- crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/gcpfirewall.go
- crd/config/crds/networking.gke.io_gcpfirewalls.yaml
Rollbacking changes in https://github.com/kubernetes/cloud-provider-gcp/pull/477/commits/88497b681ff7f2afb0f78da6b8c9cb8c6d6d3894
This is to avoid creating any resources in customer
namespaces.
> Revert GCPFirewall CRD back to Cluster scoped

- cmd/gke-gcloud-auth-plugin/cred.go
- cmd/gke-gcloud-auth-plugin/cred_test.go
- cmd/gke-gcloud-auth-plugin/gcloud_token_provider.go
Remove expiry checking from access tokens returned from gcloud tool. This will allow for gcloud access token retrievals where there is no expiry time stamp. But, this also means, we are not able to verify validity of these tokens when cached. So, we are not caching these tokens.
> Remove expiry checking from access tokens returned from gcloud tool

- crd/apis/network/v1/network_types.go
- crd/apis/network/v1alpha1/network_types.go
- crd/config/crds/networking.gke.io_networks.yaml
This is to support device-typed networks, working in conjunction with `deviceMode` in gkenetworkparams.
> Adds "device" type network

- providers/gce/support.go
* adds support for a new cloud.RateLimiter interface func so that gceRateLimiter can continue to satisfy the interface.
* This unblocks importers of legacy-cloud-provider (i.e. kubernetes/ingress-gce) from updating their k8s-cloud-provider version.
This PR replaces https://github.com/kubernetes/kubernetes/pull/116448
/assign @aojea
> Extend gceRateLimiter to satisfy cloud.RateLimiter

- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator_test.go
For host networks, GKENewtorkParamSet will not have any pod ranges configured. This PR adds a nil check on PodIPv4Ranges before going through secondary ranges.
> Handle missing PodIPv4Ranges in GKENetworkParamSet

- cmd/gcp-controller-manager/dpwi/configmap/BUILD
- cmd/gcp-controller-manager/dpwi/configmap/configmap.go
- cmd/gcp-controller-manager/dpwi/hms/BUILD
- cmd/gcp-controller-manager/dpwi/hms/hms.go
- cmd/gcp-controller-manager/dpwi/serviceaccounts/BUILD
- cmd/gcp-controller-manager/dpwi/serviceaccounts/types.go
We plan to refactor DPWI (Direct Path via ALTS with Workload Identity). The new code path will be inside a new folder "dpwi". To mitigate the migration risk, we will keep the old code path and use a flag to switch the old/new code path.
Git doesn't support copy. To preserve the git history, I followed [Record file copy operation with Git](https://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git/46484848#46484848) and achieved it with 4 steps (commits).
* [Move DPWI related code from main into the folder dpwi](https://github.com/kubernetes/cloud-provider-gcp/commit/27f6096386527b12f1a2bd67e2f9b300587a3f51)
* [Restore DPWI related code in main package](https://github.com/kubernetes/cloud-provider-gcp/commit/7ae46bf7040a7657603e8b83ae7ac2bf01bdf63d)
* [Merge branch to …
> Duplicate DPWI Related Code into a new folder dpwi as Refactor Preparation

- cmd/cloud-controller-manager/gkenetworkparamsetcontroller.go
- crd/apis/network/v1alpha1/gkenetworkparamset_types.go
- crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
- pkg/controller/gkenetworkparamset/BUILD
- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
This is the first PR of many to add validation and robustness to the Network and GNP lifecycle. There will be fast follow PRs, this is the first one to be split out for ease of review.
- Places a finalizer on GNP if it doesn't have one from CCM. This is for use in the deletion flow later.
- Adds NetworkName to the GNP status object. This is for use in a later PR.
> GNP Controller add finalizer on GNP creation & Add Network Name to GNP type.

- cmd/cloud-controller-manager/main.go
With this changes
```
--controllers strings                                                                                                                                                
A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named
'foo'.
All controllers: cloud-node, cloud-node-lifecycle, gkenetworkparamset, nodeipam, route, service
Disabled-by-default controllers: gkenetworkparamset (default [*])
```
Fixes: https://github.com/kubernetes/cloud-provider-gcp/issues/459
> disable gkenetworkparamset controller by default

- WORKSPACE
This is mainly to patch https://security-tracker.debian.org/tracker/CVE-2023-24538
> Update go SDK to 1.19.9 as 1.19.6 has vulnerabilities

- crd/apis/network/v1/annotations.go
- crd/apis/network/v1/annotations_test.go
Adding API support for nic-info annotation. nic-info holds the mapping between the NIC's first v4 IP and its PCI address on the node, along with interface's birth name.
> Adding API support for nic-info annotation

- cloudbuild.yaml
This allows to build images and tag them with the released version
https://github.com/kubernetes/test-infra/blob/4b2a5cedb3ce0a2ef1148e1831cad5d48334258a/config/jobs/image-pushing/README.md?plain=1#L35-L38
> `_PULL_BASE_REF` will contain the base ref that was pushed to - for instance,
`master` or `release-0.2` for a PR merge, or `v0.2` for a tag. You can use this
for logic in your build process (like deciding whether to update `latest`) if
desired.
> use the tag version to build the images

- providers/gce/BUILD
- providers/gce/gce_loadbalancer.go
- providers/gce/gce_loadbalancer_test.go
- providers/gce/gce_util.go
The external cloud provider controller for loadbalancers does not support Services with different protocols and most probably it will never support them, since most of the functionality and development for loadbalancers is being done in the ingress-gce project.
Current code assumes that is not possible to have multiple protocols in multiple places
https://github.com/kubernetes/cloud-provider-gcp/blob/a87489673c598a51cc780e4eb5f9d397c6fa2485/providers/gce/gce_loadbalancer_external.go#L1043-L1050
https://github.com/kubernetes/cloud-provider-gcp/blob/a87489673c598a51cc780e4eb5f9d397c6fa2485/providers/gce/gce_loadbalancer_internal.go#L857-L858
Code borrowed from the cloud-provider-aws, thanks 
Ref: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/1435-mixed-protocol-lb …
> don't process unsupported loadbalancers with mixed protocols

- pkg/controller/gkenetworkparamset/BUILD
- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
This PR prevents the deletion of a GNP object if the back referenced network both exists and is in use. If the network no longer exists or no reference was ever stored, we allow the object to be deleted.
> Add GNP Delete Handling

- cluster/common.sh
- cluster/gce/gci/configure.sh
- cluster/gce/upgrade.sh
- cluster/gce/util.sh
- cluster/get-kube-binaries.sh
- cluster/get-kube.sh
- e2e/scenarios/kops-simple
/kind cleanup
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
> fix: use dl.k8s.io, not kubernetes-release bucket

- crd/apis/network/v1/network_types.go
- pkg/controller/nodeipam/ipam/BUILD
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator_test.go
NOTE: This PR is originally from #532, I will be owning its review and making necessary modifications to get it merged based on comments. I have reviewed the original PR and have approved.
This change accounts for Network Ready condition and Node's network-status annotation.
The north-interface annotation is set only for Ready Networks. The networks annotation and IP capacity is set for networks in network-status annotation.
Added new reconcile triggers:
- Node MN network-status annotation change
- Network Ready condition state change
> Modify Multi-network annotation generation.

- cloudbuild.yaml
Artifacts is a global option
https://cloud.google.com/build/docs/building/store-artifacts-in-cloud-storage
the job fails because the current config is wrong https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cloud-provider-gcp-push-images/1660833522828447744
> fix cloudbuild

- crd/apis/network/v1/gkenetworkparamset_types.go
- crd/apis/network/v1/network_types.go
Adding omitempty to device mode should fix the following:
```spec.deviceMode: Unsupported value: \"\": supported values: \"DPDK-VFIO\", \"NetDevice\""```
We need to provide a reason for when Conditions are true, so they are being added here.
There will be a followup PR for using the new conditions. I'm specifically segmenting crd package changes so they can be pulled in elsewhere.
> Add missing network condition reasons & omitempty devicemode

- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
This change will process all Ready Networks, even if those are being deleted. We will rely on delete event for Network for cleanup.
> Remove DeletionTimestamp filtering for Networks to process.

- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
In ParametersRef for Network objects kind match does not need to be case sensitive. This is a basic usability improvement.
> Change GNP controller to ignore case for Network kind match

- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
- pkg/util/node/BUILD
- pkg/util/node/node.go
* Updated event triggers for Network updates to handle the new Conditions introduced. When Condition Ready becomes `true` it should be treated same as Network added.
* Small update to when we update the Node for network annotation and Capacity, it should only be done when there are no errors.
* changed API updates for annotations, separated from Capacity updates, and created additional API call so that we could perform StrategicMergePatchType for annotations.
> Additional fixes for Multi-Network handling.

- WORKSPACE
1.20.5 has fixes for CVE-2023-29402 CVE-2023-29403 CVE-2023-29404 CVE-2023-29405
> update go version to 1.20.5

- providers/gce/support.go
I added simple call to Subnetworks.Get to ingress-gce https://github.com/kubernetes/ingress-gce/blob/4e0e607834fd40a18d74e9241ba0a28e237f1875/pkg/utils/utils.go#L934 and found on tests that it fails on xpn scenario. Which makes sense -- project id of subnetwork in case of XPN is different, than just project ID
Looks like we never called Subnetworks.Get before (at least I could not find usages)
This PR should fix this, and give ability to get Subnetwork from the NetworkProject
> Return NetworkProjectID() as a project ID for Subnetworks resource

- WORKSPACE
fixes [CVE-2023-29406](https://security-tracker.debian.org/tracker/CVE-2023-29406)
/cc @aojea 
/cc @mikedanese
> update go version to 1.20.6

- providers/gce/gce_loadbalancer.go
- providers/gce/gce_loadbalancer_test.go
Default load balancer implementations should ignore services that set LoadBalancerClass field.
> L4 LoadBalancers - ignore services that specify LoadBalancerClass

- WORKSPACE
Addresses CVE-2023-39533 and CVE-2023-29409, although neither seem to be exploitable within the context of the GKE components in this repo.
> Bump Go version to 1.20.7

- .ko.yaml
- tools/common
- tools/push-images
As a safe way of removing bazel, start creating a parallel build
environment that is more amenable to the normal k8s release process.
> Simple build scripts for cloud-controller-manager

- WORKSPACE
Ensure that (overzealous) scanners stay quiet.
> Bump go to 1.20.8

- cloudbuild.yaml
This plugs in our simpler (bazel-free) scripts into the release build.
> Use simpler build in cloudbuild

- cmd/cloud-controller-manager/main.go
Otherwise it cannot be enabled/disabled, because that operates on the
canonical name only.
> Register nodeipam controller under canonical name

- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Add support for IPv6 only Nodes to the CloudAllocator IPAM controller
Change-Id: Ibaaefb7024e83fe0b5a16b1519aa7acd918027ac
> cloudAllocator ipv6 only ipam

- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
The gcp-controller, to avoid issues with preemtible VMs, detect when a VM has changed and delete all Pods associated to avoid Kubernetes controllers think this was a restart, when it actually was a completely replacement of the VM.
The heuristic for detecting a Node change are based on:
- the instance ID, that is unique for each instance
- the pod.Spec.PodCIDRs value
The logic for the PodCIDR value is not easy to generalize and current implementation is based on a specific implementation and configuration. In addition, the pod.Spec.PodCIDRs field is inmutable once set, so it can only change if the VM is new, ie. the instanceID has changed, so no need to duplicate the logic.
Fixes: #609
> gcp-controller: don't make assumptions on PodCIDRs

- cloudbuild.yaml
- add tags to cloudbuild job to make it easier to find in the gcp console
the gcp project is shared with other projects like `gcp-compute-persistent-disk-csi-driver` and in cloudbuild is hard to find the job that belong to cloud-provider-gcp, so adding some tags will be easier 😄 
/assign @aojea
> add tags to cloudbuild job to make it easier to find in the gcp console

- tools/push-images
If the tag has a forwards slash like `ccm/v0.0.1`, we will only build
images for the `ccm` component (and similarly for other components).
sha based tags will continue to build images for all components.
> push-images now honors component names in tags

- pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
- providers/gce/support.go
CCM does not have the compute.networks.get permission for the host network. This causes the validation to fail on the GCE call. This can be ignored for XPN clusters
> Skip the VPC validation for XPN clusters in GNP controller

- cmd/gcp-controller-manager/node_csr_approver.go
- cmd/gcp-controller-manager/node_csr_approver_test.go
Support owner references that point directly to the `instanceGroupManagers` objects in the API.
> Support owner references that point directly to instanceGroupManagers.

- providers/gce/gce_loadbalancer.go
- providers/gce/gce_loadbalancer_test.go
This reverts commit a5df7a381a10c965db03889fbc46a62f0bbd073d.
The original logic was correct
We have E2E tests that verify the original logic
> Rollback PR#598 "Fix ILB deletion by checking for finalizer"

- crd/apis/network/v1/gkenetworkparamset_types.go
This PR is for supporting Multi Pod CIDR with Multi-networking clusters. 
GNP controller will use the added constants.
> Add constants to Network CRD

- WORKSPACE
- cloudbuild.yaml
Scanners detect, e.g., CVE-2023-45285 and CVE-2023-39326 in go1.20.10, irrespective of their applicability to this binary.
> Update to go1.20.12

- cmd/cloud-controller-manager/BUILD
- cmd/cloud-controller-manager/nodeipamcontroller.go
- cmd/cloud-controller-manager/nodeipamcontroller_test.go
- pkg/controller/nodeipam/ipam/cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
- pkg/controller/nodeipam/node_ipam_controller_test.go
Use service CIDR flag to determine the right cluster stack type, and assign the right PodCIDRs to the node object.
This fixes a problem where a single-stack IPv4 cluster on a dual-stack GCE network actually gets both IPv4 and IPv6 Pod CIDRs. Additionally, single-stack IPv6 clusters are now supported.
> Configure Pod CIDRs based on service CIDRs

- cmd/gcp-controller-manager/main.go
We expose these params as CLI flags instead of using hardcoded values. Original hardcoded values are used as default values for the flags.
> Add CLI flag for kubeconfig QPS and burst in gcp-controller-manager

- cmd/gke-exec-auth-plugin/BUILD
- cmd/gke-exec-auth-plugin/main.go
- cmd/gke-exec-auth-plugin/vm_token.go
cc @zshihang 
Adds a vm-token mode for fetching vm tokens.
This provides tokens identical to those provided by the `gcp` auth-provider removed from kubernetes/kubernetes.
This is an additive token fetching mode that can be used by any kubernetes version that supports exec auth plugins with the v1beta1 API (1.11+, I think)
> Add VM token mode

- providers/gce/gce.go
- providers/gce/gce_fake.go
- providers/gce/gce_instances.go
- providers/gce/gce_instances_test.go
/assign @aojea 
/assign @marqc
> Order node addresses based on cluster stack type

- cmd/gcp-controller-manager/loops.go
- cmd/gcp-controller-manager/node_annotator.go
- cmd/gcp-controller-manager/node_annotator_test.go
All of the VMs provisioned by Provisioning Requests have bounded TTL, which is 7 days by default and can be lowered by users via `maxRunDurationSeconds` in Provisioning Request (https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest).
We would like to surface information about TTL to the GKE users using k8s API, as it is not presented to them directly.
> Add VM termination annotation; switch to Compute Beta API

- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/network_tiers.go
* Migrates e2e tests for service network tiers from in-tree to `cloud-provider-gcp`
* Previous file location (at `v1.30`): https://github.com/kubernetes/kubernetes/blob/release-1.30/test/e2e/network/network_tiers.go
> e2e tests for network tiers

- cmd/gcp-controller-manager/ca_cache_test.go
Parallel test closures execute in a goroutine, possibly after the next
loop iteration has already began. As a result, the loop var they
capture changes before the test execute, leading to all of them
executing just the last test in the map.
This fixes that by making the closure capture local variables rather
than the loop variables
See similar main kubernetes repo PR https://github.com/kubernetes/kubernetes/pull/111846
> Fix broken `TestCACacheVerify` test

- crd/apis/network/v1/gkenetworkparamset_types.go
- crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Added NetworkAttachment to GKENetworkParamSet CRD to support network attachments to connect to instead of a VPC-subnet pair.
> Add NetworkAttachment to GKENetworkParamSet CRD

- providers/gce/gce_loadbalancer_internal.go
- providers/gce/gce_loadbalancer_internal_test.go
- providers/gce/gce_loadbalancer_utils_test.go
Cherry-pick #679
L4 ILB - skip nodes from the non default network if multi subnet is turned on.
(cherry picked from commit 543f0b63c987c1775892859a8b82e1d7ebbdd19d)
> [Cherry-pick #679 to release-1.30] L4 ILB - skip nodes from the non default network if multi subnet is turned on.

- providers/gce/gcpcredential/gcpcredential.go
There are valid docker repositories at "docker.UNIVERSE_NAME.goog" that are valid and we have had a request to add those to our list of repo urls.
> Add another valid container repository to our list.

- providers/gce/gce_loadbalancer_internal.go
- providers/gce/gce_loadbalancer_internal_test.go
- providers/gce/gce_loadbalancer_utils_test.go
Cherry-pick #679 to release-1.29
L4 ILB - skip nodes from the non default network if multi subnet is turned on.
> Cherry-pick #679 to release-1.29

- providers/gce/gce.go
- providers/gce/gce_fake.go
- providers/gce/gce_instances.go
- providers/gce/gce_instances_test.go
[Cherrypick #689] Order node addresses based on cluster stack type
(cherry picked from commit 1dc6be82077dfc161167be71ad6fe306080a389c)
> [Cherrypick #689 to release-1.29] Order node addresses based on cluster stack type

- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
- pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
Different node pools can have NICs on the same VPC but different subnet. This should be allowd
> Allow multiple device networks to have the same VPC

- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
For network attachment network interfaces, nodes get IPs as usual, but we need to get pod CIDRs from the alias ranges from the interface. The alias ranges are not named, and there must be only one alias range per network attachment interface.
> Handle CIDR allocation for network attachments

- providers/gce/gce.go
- providers/gce/gce_instances.go
Solves #758
If we add a new node from another zone in single zone mode (without multizone=true in cloud config), the CCM can't find it because CCM searches for it only in one zone where CCM runs. Then after one minute of trying CCM removes the new uninitialised node from the cluster.
I propose to add some logs to make it clear what happens.
> Print logs when adding a node in unmanaged zone

- cmd/cloud-controller-manager/gkenetworkparamsetcontroller.go
- cmd/cloud-controller-manager/nodeipamcontroller.go
For core K8s APIs, `cloud-node`, `cloud-node-lifecycle`, `service` and `route` controllers fetch informers from the completed config rather than from the controller context (e.g. [here](https://github.com/kubernetes/kubernetes/blob/283ff763b3fd82c831f1f45efa87fb2aa518d184/staging/src/k8s.io/cloud-provider/app/core.go#L45)), so we basically mimic that behavior with this change.
This gives us two small performance gains:
- We deduplicate the API traffic by opening less watches from the CCM,
- Shared informers from the completed config use protobuf encoding instead of the (less efficient) JSON encoding.
- The fact that these informers use protobuf comes from the  that CCM's config defaulting runs defaulting for [generic CM config](https://github.com/kubernetes/kubernetes/blob/283ff763b3fd82c8 …
> Reuse shared informers in nodeipam and gkenetworkparamset controllers

- cmd/auth-provider-gcp/provider/provider.go
- cmd/auth-provider-gcp/provider/provider_test.go
- pkg/gcpcredential/gcpcredential.go
We will have the credential provider unconditionally attach the the access token to the registry in the image request, and then rely on the Kubelet config to restrict which registries the access token will be sent to
> Allow ContainerRegistryProvider to skip Match ContainerRegistryUrls when query the token

- WORKSPACE
- cloudbuild.yaml
> Bump Go version to 1.23.1 (CVE-2024-34156, CVE-2024-34155, CVE-2024-34158, CVE-2024-24791)

- tools/push-images
Remove the build for cmd/gcp-controller-manager as all files under that path have been removed in #770
> Remove gcp-controller-manager from tools-push-images

- README.md
Similar to https://github.com/kubernetes/cloud-provider-gcp/pull/797
> remove gcp-controller-manager from readme

- README.md
The default registry is changed from `gcr.io` to `registry.k8s.io`
https://github.com/kubernetes/cloud-provider-gcp/commit/131cd79e47a50626910b895359ce456be783c1b8
---------------
Verified the up the `push-images` command:
```
IMAGE_REPO=us-central1-docker.pkg.dev/zivy-gke-dev-2/ccm-test IMAGE_TAG=v0 ./tools/push-images
Published us-central1-docker.pkg.dev/zivy-gke-dev-2/ccm-test/gcp-controller-manager:v0@sha256:fea460f6a2d11fb5a7e0172ba46665481bca4e555d8b65c91d930b0ee30058b4
us-central1-docker.pkg.dev/zivy-gke-dev-2/ccm-test/gcp-controller-manager:v0@sha256:fea460f6a2d11fb5a7e0172ba46665481bca4e555d8b65c91d930b0ee30058b4
```
Also the purpose is to encourage people to use artifact registry. Container registry is deprecated and is on migration. See …
> README: fix push image doc, and add push-image tool

- providers/gce/gce_loadbalancer_internal.go
- providers/gce/gce_loadbalancer_internal_test.go
Fix(ILB): Prevent deletion of nodes with empty zone label
Previously, new nodes were created with all topology labels present, including the zone label. However, recently, labels are being patched/updated on the node resource *after* the resource is created. This can result in nodes having an empty zone field when initially added to an instance group.
The Internal Load Balancer controller was incorrectly removing these nodes with empty zone labels from their assigned instance groups. This occurred because the controller interpreted nodes with empty zones as not belonging to any zone.
This commit fixes the issue by:
- Storing nodes with empty zones during node processing.
- Preventing the controller from removing these nodes during zone processing.
This ensures that new nodes with …
> Internal Load Balancer Controller do NOT remove nodes with empty string in the zone field

- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
- pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
We shouldn't allow GNP deletion when there is still network refering to it.
Once GNP is removed, the network is removed from north-interface annotation. Other controllers won't be able to reconcile the network on the node anymore to clean up
> avoid GNP deletion when network is refering to it

- e2e/scenarios/kops-simple
Updating after the move to community infrastructure.
-----------------
backport of https://github.com/kubernetes/cloud-provider-gcp/pull/766
> e2e: update path to kOps marker files (1.30 backport)

- cloudbuild.yaml
[Job](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-cloud-provider-gcp-push-images/1894330882576093184) failed to push image, error
```
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid build tag "ccm/v32.2.0": must match format "^[\\w][\\w.-]{0,127}$"
2025/02/25 10:17:53 Failed to run some build jobs: [error running [gcloud builds submit --verbosity info --config /home/prow/go/src/github.com/kubernetes/cloud-provider-gcp/cloudbuild.yaml --substitutions _PULL_BASE_REF=ccm/v32.2.0,_GIT_TAG=v20250225-ccmv32.2.0 --project k8s-staging-cloud-provider-gcp --gcs-log-dir gs://k8s-staging-cloud-provider-gcp-gcb/logs --gcs-source-staging-dir gs://k8s-staging-cloud-provider-gcp-gcb/source gs://k8s-staging-cloud-provider-gcp-gcb/source/25081eab-adf5-49a0-bac5-8f6d730c9b …
```
> Fix cloudbuild tag cause push OSS image job failure

- .gitignore
- cmd/cloud-controller-manager/main.go
- providers/gce/gce.go
- providers/gce/gce_instances.go
- providers/gce/gce_instances_test.go
* Introduce a multiProject option in GCE Cloud Provider, such that when enabled, the project derived by parsing the Node's `.spec.providerID` will be used for subsequent GCE API calls. The option should only be enabled when the `.spec.providerID` can be trusted.
* Introduce a corresponding CLI flag for Cloud Controller Manager command which will control the enablement of multiProject option in the instantiated GCE Cloud Provider.
* **Safeguard:** This is an opt-in change: The default behaviour of ignoring the project value is maintained.
---
(This PR builds on top of the work done in https://github.com/kubernetes/cloud-provider-gcp/pull/779 by @hoskeri)
> Add a multiProject option to GCE Cloud Provider

- go.mod
- go.sum
- vendor/github.com/GoogleCloudPlatform/gke-networking-api/apis/network/v1/annotations.go
- vendor/modules.txt
To use nodetopology [CRD](https://github.com/GoogleCloudPlatform/gke-networking-api/pull/22), upgrade `gke-networking-api` version.
`
go get github.com/GoogleCloudPlatform/gke-networking-api@bc15495fd43f01b9d0cc9e244f71d024d81450d4 && ./tools/update_vendor.sh
`
cc. @basantsa1989 @sawsa307
> update gke-networking-api in order to use nodetopology CRD

- pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
The original CCM triggers listing for GNP in an unnecessary frequency.
This change modify the listing logic.
> Improve CCM listing behavior for GNP object 

- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
- pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
- pkg/util/node/node.go
CCM watches and updates Multi-Network annotations and resources. It should trigger node reconciliation whenever those fields changes
Also add logs to show actual patches applied when updating multi-network information
> Trigger node reconciliation if MultiNetwork info changed

- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
- pkg/util/node/node.go
From scalablity test, I notice sometimes PatchNodeMultiNetwork() hangs due to overloaded api-server, leaving node capacity incorrect while the annotation is patched. The node will never get patched again because we don't patch a node if annotation is already correct.
Fixed the issue by:
* apply capacity patch when there is update only to node capacity
* add a timeout to PatchNodeMultiNetwork to unblock the goroutine
> fix partial multinetwork node patch

- tools/verify-govet.sh
verify-govet.sh is running in parallel for all targets, resulting in huge resource consumption. There are only 2 cpus and 4GiB memory allocated. The test is actually gettting OOM killed https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/cloud-provider-gcp/817/cloud-provider-gcp-verify-all/1899821170069344256
Changed to run go vet in serial, which can finish on my computer in 10 mins
> don't run go vet in parallel

- Dockerfile
- tools/push-images
Fixes: https://github.com/kubernetes/cloud-provider-gcp/issues/821
/assign @cpanato @YifeiZhuang 
This changes the way of building the image from `ko` to `Dockerfile`, despite `ko` is really simple and useful the app path inside the container is hardcoded and this cause conflict with all the existing ecosystem that depend in the app path to work
Instead of using bazel, that is something we'd like to get rid of, let's use a Dockerfile that is the standard and in this is case is very simple
> use docker build to generate images

- cmd/cloud-controller-manager/main.go
- providers/gce/gce.go
- providers/gce/gce_loadbalancer_external.go
- providers/gce/gce_loadbalancer_external_test.go
GCE forwarding rules have a limit of 5 forwarding ports. In the external L4 load balancer, we currently turn a set of exposed ports into a port range from minPort to maxPort and forward all ports in the range. With this change we match the service definition better to forward individual ports when possible.
> Forward individual ports for NetLB with 5 or less service ports

- cloudbuild.yaml
- tools/push-images
1. [post-submit job](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-cloud-provider-gcp-push-images/1906855542492499968) execution failure:
```
Step #0: tools/push-images: line 48: docker: command not found
```
Fix https://github.com/kubernetes/cloud-provider-gcp/pull/825
2. Then, after docker command is fixed in 1, fix error `unknown flag: --push`
```
docker build --push -t us-central1-docker.pkg.dev/zivy-gke-dev-2/ccm-test/cloud-controller-manager:29387948793 .
unknown flag: --push
```
--------------
Tested using `gcloud builds submit  --config=cloudbuild1.yaml .` (creating empty `.gcloudignore`)
> fix publish image cloudbuild job failure docker not found, unknown flag: --push

- cmd/cloud-controller-manager/main.go
- providers/gce/gce.go
- providers/gce/gce_loadbalancer_external.go
- providers/gce/gce_loadbalancer_external_test.go
GCE forwarding rules have a limit of 5 forwarding ports. In the external L4 load balancer, we currently turn a set of exposed ports into a port range from minPort to maxPort and forward all ports in the range. With this change we match the service definition better to forward individual ports when possible.
> [Cherry-pick #826 to release-1.32] Forward individual ports for NetLB with 5 or less service ports

- Dockerfile
- tools/push-images
> use docker build to generate images(1.32 backport)

- cloudbuild.yaml
- tools/push-images
backport of change: https://github.com/kubernetes/cloud-provider-gcp/pull/829
----------------
The image is probably still not really usable see comments: https://github.com/kubernetes/cloud-provider-gcp/pull/830
/assign @mmamczur 
cc. @aojea
> [1.32 backport]fix publish image cloudbuild job failure docker not found, unknown flag: --push 

- providers/gce/gce_annotations.go
- providers/gce/gce_loadbalancer.go
- providers/gce/gce_loadbalancer_external.go
- providers/gce/gce_loadbalancer_external_test.go
- providers/gce/gce_loadbalancer_internal.go
- providers/gce/gce_loadbalancer_internal_test.go
- providers/gce/gce_loadbalancer_test.go
- providers/gce/gce_loadbalancer_utils_test.go
- providers/gce/gce_util.go
This PR implements support for the `spec.loadBalancerClass` field in Kubernetes Services for Layer 4 load balancers. This change enables users to explicitl specify the controller responsible for managing their LoadBalancer services, providing greater flexibility and control.
> Implement loadBalancerClass support for L4 Service selection

- providers/gce/gce_annotations.go
- providers/gce/gce_loadbalancer.go
- providers/gce/gce_loadbalancer_external.go
- providers/gce/gce_loadbalancer_external_test.go
- providers/gce/gce_loadbalancer_internal.go
- providers/gce/gce_loadbalancer_internal_test.go
- providers/gce/gce_loadbalancer_test.go
- providers/gce/gce_loadbalancer_utils_test.go
- providers/gce/gce_util.go
This PR implements support for the `spec.loadBalancerClass` field in Kubernetes Services for Layer 4 load balancers. This change enables users to explicitl specify the controller responsible for managing their LoadBalancer services, providing greater flexibility and control.
> [Cherry-pick #834 to release-1.32] Implement loadBalancerClass support for L4 Service selection

- Dockerfile
This helps with caching, but also avoids adding go.work during tests.
> Dockerfile: copy precise dependencies

- Dockerfile
The introduction of the Dockerfile had changed the entrypoint to
ko-runner, breaking manifests that did not override the entrypoint.
Restore the old behaviour where specifying the entrypoint was optional.
> fix: Dockerfile should set entrypoint

- providers/gce/gce_loadbalancer_external.go
- providers/gce/gce_loadbalancer_external_test.go
- providers/gce/gce_loadbalancer_internal_test.go
- providers/gce/gce_loadbalancer_test.go
- providers/gce/gce_loadbalancer_utils_test.go
- providers/gce/gce_util.go
This change introduces the `NetLBFinalizerV1` ("gke.networking.io/l4-netlb-v1") to Kubernetes Service objects of type LoadBalancer managed by the legacy cloud-controller-manager logic for external L4 Network Load Balancers (NetLB).
**Controller Distinction:** It clearly marks the Service as being managed
by this specific controller logic (`ensureExternalLoadBalancer`),
distinguishing it from services managed by newer controllers using
Regional Backend Services (RBS), which use `NetLBFinalizerV2` or
`NetLBFinalizerV3`. The `usesL4RBS` function now explicitly checks
for the absence of V1 finalizer as one condition to determine if a
service *might* be managed elsewhere.
Implementation details:
- The `NetLBFinalizerV1` is added to the Service metadata within the `ensureExternalLoadBalancer` …
> feat(provider/gcp): Add NetLBFinalizerV1 to legacy L4 LB services

- Dockerfile
- e2e/add-kubernetes-to-workspace.sh
- e2e/scenarios/kops-simple
We want to test with the same build that we are now using
to publish images.
> e2e: ensure kops e2e uses push-images script

- Dockerfile
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-cloud-provider-gcp-push-images/1915465901432377344:
```
Step #0: Step 7/17 : COPY go.mod go.sum .
Step #0: When using COPY with more than one source file, the destination must be a directory and end with a /
```
Related to https://github.com/kubernetes/cloud-provider-gcp/pull/838
Tested locally 
```
IMAGE_REPO=<something> IMAGE_TAG=<something> ./tools/push-images
```
> fix docker file COPY

- WORKSPACE
Fix https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-cloud-provider-gcp-push-images/1915536523495739392
/label tide/merge-method-squash
> bazel build: use go 1.24 in go_sdk

- providers/gce/gce_annotations.go
- providers/gce/gce_loadbalancer.go
- providers/gce/gce_loadbalancer_external.go
- providers/gce/gce_loadbalancer_external_test.go
- providers/gce/gce_loadbalancer_internal.go
- providers/gce/gce_loadbalancer_internal_test.go
- providers/gce/gce_loadbalancer_test.go
- providers/gce/gce_loadbalancer_utils_test.go
- providers/gce/gce_util.go
Reverts kubernetes/cloud-provider-gcp#840
Changes cherry-picked to release 1.32 are no longer needed and were never released. This behavior is not expected to be supported in 1.32 for now. Removing them from this release to keep it clean and prevent releasing this changes which are not needed if a necessary backport is needed.
> Revert "[Cherry-pick #834 to release-1.32] Implement loadBalancerClass support for L4 Service selection"

- WORKSPACE
cherry pick of https://github.com/kubernetes/cloud-provider-gcp/pull/858
The post submit job has been fixed after #858
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-cloud-provider-gcp-push-images
/label tide/merge-method-squash
/cc @XuanWang-Amos
/assign @mmamczur
> bazel build: use go 1.24 in go_sdk (1.33 backport)

- providers/gce/gce_loadbalancer.go
Adding finalizer-netlb-v1 check when checking if NetLB exists. 
If FR was deleted but deletion call fails, the controller will think the LB does not exist anymore and it will skip cleaning up the Target Pool.
Since Finalizer V1 is removed only when all the resources are successfully cleaned up we can use it to know if something is left to clean up.
> Fix: Target Pool are leaked when Forwarding Rule fails deletion

- pkg/controller/nodeipam/ipam/task_queue_test.go
example - go test -count=1 -race -v $(go list ./...)
Complete log [data](https://www.diffchecker.com/NUVo0Bj3/) , left ( failed without fix) right (Passed with fix)
> Adding SyncMutex as unit tests is failing when detecting race

- providers/gce/gce_loadbalancer_test.go
This PR enhances the TestGetLoadBalancer function by adding a test case to verify its behavior when a Service has a finalizer, but the underlying cloud resource has already been deleted.
Motivation:
The GetLoadBalancer function has specific logic to handle the cleanup phase of a LoadBalancer. When a service is being deleted, it might still have a finalizer (e.g., NetLBFinalizerV1) even after the actual GCE forwarding rule is gone.
In this state, GetLoadBalancer should correctly report that the resource still exists (found=true) to ensure the controller completes the cleanup process gracefully. The existing tests did not explicitly cover this important lifecycle state.
Changes:
After the load balancer is deleted in the test, a finalizer is manually added back to the service object.
New …
> TestGetLoadBalancer improvement: finalizer check logic in GetLoadBalancer

- providers/gce/gce_loadbalancer_utils_test.go
This is checked in newer versions of go
> tests: fix linting problem

- cmd/cloud-controller-manager/nodeipamcontroller.go
- cmd/cloud-controller-manager/options/nodeipamcontroller.go
- pkg/controller/nodeipam/config/types.go
- pkg/controller/nodeipam/ipam/cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
- pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
- pkg/controller/nodeipam/node_ipam_controller.go
- pkg/controller/nodeipam/node_ipam_controller_test.go
The current way in cloud-controller-manager to determine multi-networking-enabled clusters is based on the number of NICs. However, as an ongoing effort to decouple multi-NIC nodes with the enableMultiNetworking flag, nodes with multi-NICs but don't have the multi-networking features enabled are incorrectly processed by multi-networking code paths. 
For logic that differs between non-multi-networking and multi-networking clusters (such as determining node's podCIDR), the direct discriminator should be the --enable-multi-networking flag. 
Introducing this enableMultiNetworking flag to CCM ensures more accurate feature logic and unblocks the creation of new multi-NIC nodes.
> Add enableMultiNetworking flag and clarify the multi-networking judgement logic
