Gopkg.lock, cmd/gcp-controller-manager/BUILD, cmd/gcp-controller-manager/app/BUILD, cmd/gcp-controller-manager/app/gke_approver.go, cmd/gcp-controller-manager/app/gke_signer.go, cmd/gcp-controller-manager/main.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD, vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
Measure count and latency per status for both signer and approver.
=> Add metrics to cert controller

cmd/gcp-controller-manager/app/controller.go, cmd/gcp-controller-manager/app/node_annotater.go, cmd/gcp-controller-manager/app/node_annotater_test.go
=> factor out annotaters so we can add more

cmd/gcp-controller-manager/app/gke_approver.go
This way we'll distinguish what kind of bootstrap flow kubelets use.
=> Add label per approval type to approver metrics

cmd/gcp-controller-manager/app/gke_approver.go, pkg/nodeidentity/id.go
Without this, VM A can impersonate VM B by requesting cert with forged
VM IDENTITY block. VM identity from AIK ties it to TPM ownership
specific VM.
=> Read VM identity from AIK cert

code-of-conduct.md
adding missing code-of-conduct.md file as suggested by kubernetes-template-project.
=> adding code-of-conduct.md

cmd/gke-exec-auth-plugin/BUILD, cmd/gke-exec-auth-plugin/cache.go, cmd/gke-exec-auth-plugin/cache_test.go, cmd/gke-exec-auth-plugin/main.go
Actually caught 2 bugs:
- corrupt existing private key would be returned
- (unlikely) expired cert that's <10d old would be returned
=> Tests for plugin caching logic

cmd/gke-exec-auth-plugin/tpm.go, cmd/gke-exec-auth-plugin/tpm_test.go
AIK certificate can fail to provision. We should still send a CSR and
let the approver use a separate channel to verify attestation.
=> Allow missing AIK certificate

cmd/gke-exec-auth-plugin/request.go
Add the function name to the comment
=> Add the function name to the comment

cmd/gcp-controller-manager/app/gke_approver.go
=> Remove unnecessary code

BUILD, WORKSPACE
Cherrypick #64 into release-1.11.0
=> Cherrypick #64 into release-1.11.0

BUILD, WORKSPACE
Cherrypick #64 into release-1.11.2
=> Cherrypick #64 into release-1.11.2

WORKSPACE, cmd/gcp-controller-manager/app/BUILD, cmd/gcp-controller-manager/app/gke_approver.go, cmd/gcp-controller-manager/app/gke_approver_test.go
Also cherry-pick the bazel build fix
=> Cherry-pick "ensure Node matches metadata before approving CSRs"

WORKSPACE
=> update go to 1.11.5

README.md, go.mod, go.sum, vendor/k8s.io/client-go/pkg/version/base.go, vendor/k8s.io/kubernetes/pkg/version/base.go, vendor/modules.txt
Fixed various checksums and updated typo in README with incorrect env var. 
Unblocks adding new dependency for future work.
=> Updated dependencies and fix README

cmd/gke-exec-auth-plugin/main.go
=> Remove VM identity doc mode from exec plugin

cmd/gcp-controller-manager/csr_approver.go, cmd/gcp-controller-manager/csr_approver_test.go, cmd/gcp-controller-manager/csr_signer.go, cmd/gcp-controller-manager/csr_signer_test.go, cmd/gcp-controller-manager/loops.go, pkg/csrmetrics/csrmetrics.go
- add CSR kind to signing metrics (same as approval has)
- report more outbound RPCs (CSR updates, Nodes get/delete)
- report measurements to correct places
Also refactor the validators a bit to reuse them in csr_signer.go.
=> Improve CSR metric reporting

cmd/gcp-controller-manager/csr_approver.go
hoist changes in https://github.com/kubernetes/kubernetes/pull/84677/commits/6a004d0c18818f79d7c294091f071706aac2d912
=> don't let kubelets request certs with email address or URI SANs

cmd/cloud-controller-manager/app/controllermanager.go, cmd/gcp-controller-manager/main.go, cmd/gcp-controller-manager/node_annotator.go, cmd/gke-exec-auth-plugin/alt_token_source.go, cmd/gke-exec-auth-plugin/cache.go, cmd/gke-exec-auth-plugin/tpm.go
No behavior changes
/assign @sambdavidson
=> Clean up a few staticcheck findings

README.md, defs/container.bzl, tools/workspace-status.sh
Fixes #126
/assign @mikedanese @sambdavidson
=> Allow override of image registry with IMAGE_REGISTRY env var

cmd/gcp-controller-manager/sa_map.go, cmd/gcp-controller-manager/service_account_verifier_test.go
To avoid json marshalling of complex key and improve space efficiency.
Change-Id: I2dab708d4cb4e27c86d33b19a4476c90cf85d038
=> Change verified-ksa-to-gsa ConfigMap data encoding.

OWNERS, SECURITY_CONTACTS, cmd/gcp-controller-manager/OWNERS, cmd/gke-exec-auth-plugin/OWNERS
/assign @mikedanese @sambdavidson
=> Remove awly from OWNERS and SECURITY_CONTACTS

cmd/gcp-controller-manager/node_annotator.go, cmd/gcp-controller-manager/node_annotator_test.go
This should prevent orphan labels when managed labels are removed during node upgrade.
Last-applied-label record is stored in annotation since it allows looser syntax than label.
=> Use three-way-merge to reconcile labels from GCE instance to K8S node

cluster/OWNERS
Add Ben and Amit to Clusters owners file.
=> Add Ben and Amit to Clusters owners file.

cluster/gce/gci/configure.sh, cluster/gce/util.sh, test/boskos.sh, test/e2e.sh
/cc @BenTheElder @cheftako 
/hold
xref: https://github.com/kubernetes/test-infra/pull/17326
=> Add basic cluster up/down e2e test.

cluster/gce/gci/configure-helper.sh
Added the config to create an K8s admin account on the master.
If you have access to the master you can now easily do things like
kubectl get nodes.
=> Added k8s admin account to the master.

cluster/log-dump/OWNERS, cluster/log-dump/log-dump.sh, cluster/log-dump/logexporter-daemonset.yaml, test/OWNERS, test/e2e.sh
=> Add logdump for e2e create.

cluster/gce/config-default.sh
Backporting kubernetes/kubernetes#82062 by k-toyoda-pi to `kubernetes/cloud-provider-gcp`
=> Fix shellcheck failure in cluster/gce/config-default.sh

WORKSPACE
Attempt to fix CI on the release-1.1.5 branch.
=> Release 1.1.5 build fix

cmd/auth-provider-gcp/app/getcredentials.go
=> Fix golint issues in credential provider

cmd/auth-provider-gcp/provider/provider.go, cmd/gcp-controller-manager/ca_cache_test.go, cmd/gcp-controller-manager/csr_approver.go, cmd/gcp-controller-manager/csr_approver_test.go, cmd/gcp-controller-manager/hms.go, cmd/gke-exec-auth-plugin/main.go, tools/verify-govet.sh
Add verify-govet.sh and fix related govet failures
=> Add verify-govet.sh

README.md, tools/update_bazel.sh
=> Document how to re-gen BUILD files in README.md

cluster/gce/gci/configure-helper.sh
Fix for https://github.com/kubernetes/kubernetes/issues/91542.
This is the cluster/ part of https://github.com/kubernetes/kubernetes/pull/97934.
=> Disable local loopback for volume host

tools/verify-golint.sh
Remove redundant dir from golint check
=> Remove redundant dir from golint check

cmd/gcp-controller-manager/csr_approver.go, cmd/gcp-controller-manager/csr_approver_test.go
When a project which is a domain-scoped (becpg.fr:api-project-243761268436) causes error in gcp-controller-manager during CSR signing: `deny CSR "csr-wddss": DNSName in CSR ("gke-becpg-saas-becpg-saas-pool-n2-1-6f27d910-q3dq.c.api-project-243761268436.becpg.fr.internal") doesn't match default DNS format on instance "gke-becpg-saas-becpg-saas-pool-n2-1-6f27d910-q3dq"`
Domain-scoped projects are deprecated and no longer supported by GCP in general.
=> Format the projectID for Domain-scoped project

.bazelrc, cmd/gke-gcloud-auth-plugin/BUILD, defs/version.bzl, tools/version.sh, tools/workspace-status.sh
* Fix version stamping so it actually works. It looks like it was copy pasted largely from k8s and not sure if it ever worked.
* Build the new gcp auth plugin as pure.
=> A few build cleanups

pkg/apis/firewall/register.go
Create a directory for the apis so that other projects can import from here.
=> Create the firewall api directory

cluster/gce/gci/configure-helper.sh
Before we write the template.
Carried over from https://github.com/kubernetes/kubernetes/pull/106319
=> don't expand $(ls -A /scrub) in PV_RECYCLER_TEMPLATE

providers/gce/gce_instances.go, providers/gce/gce_instances_test.go
This patch uses the GA API to get GCE instances instead of the alpha API. The changes that were required from the alpha API have now been migrated to GA.
=> Use the GA compute API even for dual stack instances

cluster/gce/util.sh
Duplicate PR kubernetes/kubernetes#106843
=> Remove unused code path in cluster/gce/util.sh

tools/version.sh
=> Bump version.sh

OWNERS
=> Add jprzychodzen to OWNERS as reviewer

docs/instruction-how-to-bump-repository.md
Instruction how to update repository to newer version.
/assing @mborsz 
FYI @Fedosin @elmiko
=> Add instruction how to update repository

cmd/gke-exec-auth-plugin/tpm.go, cmd/gke-gcloud-auth-plugin/cred/cred.go, cmd/gke-gcloud-auth-plugin/cred/default_credentials_token_provider.go, cmd/gke-gcloud-auth-plugin/cred/gcloud_token_provider.go, crd/client/gcpfirewall/clientset/versioned/fake/register.go, crd/client/gcpfirewall/clientset/versioned/scheme/register.go, pkg/controller/nodeipam/ipam/doc.go, pkg/credentialconfig/config.go, pkg/csrapproval/csrapproval.go, pkg/gcpcredential/gcpcredential.go, providers/gce/gce_util.go
Run go1.19rc2 fmt ./... as the repo got upgraded to using go1.19rc2 and go fmt output changed!
=> Run go1.19rc2 fmt ./... as the repo got upgraded to using go1.19rc2 and go fmt output changed!

providers/gce/gce_instances.go, providers/gce/gce_instances_test.go
Removing dependency on stack type input from gce for reading IPv6 addresses from nodes.
We will always try to get IPv6 addresses from the nodes. If the node is single stack IPv4, we will ignore the null IPv6 addresses.
The gce will create the nodes with correct stack type and we solely rely on it.
This change will help us in avoiding master restarts when we change stack types.
=> Remove dependency on stacktype input from gce

cluster/gce/gci/configure-helper.sh
Fixes https://github.com/kubernetes/kubernetes/issues/112194
See related PR https://github.com/kubernetes/kubernetes/pull/112195.
=> Remove race betwen kubelet startup and mounter rootfs

cmd/gcp-controller-manager/BUILD, cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go, cmd/gcp-controller-manager/kubelet_readonly_csr_approver_test.go, cmd/gcp-controller-manager/loops.go, cmd/gcp-controller-manager/main.go
Create infra for read only resource, it will loop all validators and approve only if all validator vote yes:
1. add three validators
2. create approver
3. add feature gate option
Tested:
Unit test
local test
=> Read only resource csr approver

cmd/gcp-controller-manager/csr_signer.go, cmd/gcp-controller-manager/csr_signer_test.go, cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go, cmd/gcp-controller-manager/kubelet_readonly_csr_approver_test.go
1. add new approver to csr signer
2. unit test for it
Tested:
Unit test
=> Add kubelet readonly csr to csr signer

cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go
1. add message help to talk why we denied and approve the csr.
Tested:
Local test
=> Add response message in kubelet_readonly_csr_approver.go

OWNERS
=> add aojea to OWNERS

cluster/gce/config-default.sh, cluster/gce/config-test.sh, cluster/gce/util.sh
/cc @andrewsykim 
Ref. #398
It seems that `util.sh` was missing `CLOUD_PROVIDER_FLAG`.
=> Pass CLOUD_PROVIDER_FLAG and set DisableKubeletCloudCredentialProviders

go.mod, go.sum, vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go, vendor/modules.txt
File missed in last v1.25.5 bump
/assign @pawbana
=> Add missing v1.25.5 bump

tools/verify-up-to-date.sh
=> Add script to verify if repository is up to date

cloudbuild.yaml
Based on:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/bazel
=> Automate cloud-controller-image-creation based on cloudbuild

tools/verify-up-to-date.sh
=> Improve logging message of tools/verify-up-to-date.sh

WORKSPACE, defs/container.bzl
Otherwise we can't build with python 3.10
=> Update bazel image rules

cloudbuild.yaml
current images tags are not really meaninful
https://console.cloud.google.com/gcr/images/k8s-staging-cloud-provider-gcp/global/cloud-controller-manager?project=k8s-staging-cloud-provider-gcp
=> use a more meaninful tag and publish :latest image

cmd/gcp-controller-manager/node_csr_approver.go, cmd/gcp-controller-manager/node_csr_approver_test.go
GKE's cluster.NodePools[].instanceGroupUrls are of the form:
https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-c/instanceGroupManagers/instance-group-1
Where as instance referrers are of the form:
https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-c/instanceGroups/instance-group-1.
So we need to convert them to the same format before comparison.
=> Fix referrer url and instance group url comparison.

.gitignore
=> Add 'cluster/bin' to '.gitignore'

crd/OWNERS, crd/README.md
=> bootstrap crd folder, used for networking crds

crd/apis/network/v1/network.go
This function has been moved to an internal repository
=> move InterfaceName function to internal component

cmd/gke-gcloud-auth-plugin/cred.go, cmd/gke-gcloud-auth-plugin/cred_test.go, cmd/gke-gcloud-auth-plugin/gcloud_token_provider.go
Add support for CLOUDSDK_AUTH_ACCESS_TOKEN to gke-gcloud-auth-plugin.
From gcloud documentation: If you already have an access token, pass the access token to the gcloud CLI:
"Set the CLOUDSDK_AUTH_ACCESS_TOKEN environment variable to the access token value"
The gke-gcloud-auth-plugin directly checks if the env variable is set and directly accesses the token saved in the env variable. This bypasses gcloud, which is very slow. The reason to bypass gcloud is, since there is no expiry timestamp returned, we cannot check if the token is valid in anyway and hence cannot cache the token, which forces us to retrieve the token everytime from gcloud or the env variable.
=> Add support for CLOUDSDK_AUTH_ACCESS_TOKEN to gke-gcloud-auth-plugin

crd/apis/gcpfirewall/v1beta1/types.go, crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall.go, crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall_client.go, crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall.go, crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall_client.go, crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/gcpfirewall.go, crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/interface.go, crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/expansion_generated.go, crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/gcpfirewall.go, crd/config/crds/networking.gke.io_gcpfirewalls.yaml
- Specify default status for the CR
- Make the CR namespace scoped
=> Update GCPFirewall CRD

WORKSPACE
Verified with `./tools/verify-all.sh`
=> bump golang version

e2e/scenarios/kops-simple, test/boskos.sh
A slight mismatch in expectations here.
=> e2e/kops: job fixes

OWNERS
I have not touched this project for a long time. I should not be in the reviewer list.
=> Remove jpbetz from OWNERS

crd/apis/network/v1/zz_generated.register.go, crd/hack/generate-groups.sh
This has been removed in #490 via https://github.com/kubernetes/cloud-provider-gcp/pull/490/commits/c70e5130101cbdd028899a026a21e07b8117f680
=> Re-add "register" to update-codegen.sh.

crd/apis/network/v1alpha1/gkenetworkparamset_types.go, crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
=> fix GKENetworkParamSet CRD

crd/apis/network/v1/gkenetworkparamset_types.go
We had a few missing validation types. This needs to be merged quickly so it can be imported into the validation PR.
=> Add more GNP validations to specification

cloudbuild.yaml
Try to build automatically all the projects in the repo
https://github.com/kubernetes/cloud-provider-gcp/issues/289
=> build all projects in the repo

cloudbuild.yaml
It turns out 3 are binaries and 2 are images
This should do the right thing for each of the targets
=> build auth binaries publish controller images

cloudbuild.yaml
Based on the output I have in my laptop
=> use the direct path to the artificats

crd/apis/network/v1/gkenetworkparamset_types.go
=> Add GNPDeleted to network apis

cloudbuild.yaml
=> Fixing the binary names for windows plugins

cluster/gce/gci/configure.sh
We applied these to the k/k master, we should do it here as well.
- https://github.com/kubernetes/kubernetes/pull/119671
- https://github.com/kubernetes/kubernetes/pull/119663
=> Fix failing tests due to CDN redirects

providers/gce/gce_instances.go, providers/gce/gce_loadbalancer.go, providers/gce/gce_loadbalancer_external.go, providers/gce/gce_loadbalancer_internal.go
This will help us debug customer issues in the future
=> Improve debug logging around instance group management

providers/gce/gce.go, providers/gce/gce_instances.go, providers/gce/gce_instances_test.go, providers/gce/gce_loadbalancer_utils_test.go
Use LabelTopologyZone rather then deprecated LabelFailureDomainBetaZone as a node's zone label
=> Use LabelTopologyZone rather then deprecated LabelFailureDomainBetaZone

cmd/gke-gcloud-auth-plugin/cred.go
also, add myself to owners to triage issues for auth plugin.
=> add stderr to returned err from cmd.Run for auth plugin

pkg/controller/nodeipam/ipam/BUILD, pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go, pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
We rely on the old vs desired node diff.
=> Removed unnecessary cidr validation.

cmd/cloud-controller-manager/nodeipamcontroller.go
The inner logic of the controller already omits these fields, do the same in the command line flags validation, otherwise it forces the user to set some parameters that will be not used if the ipam controller is the CloudAllocator
Change-Id: I5c210ba8b56e13bf1029322c9a71063651d984fb
=> ipam: CloudAllocator does not require service or cluster cidr

cmd/gcp-controller-manager/loops.go, cmd/gcp-controller-manager/main.go, cmd/gcp-controller-manager/node_csr_approver.go, cmd/gcp-controller-manager/node_csr_approver_test.go
The exponential backoff parameters are configurable by the binary parameters:
* initial retry duration
* maximum retry duration
* maximal end-to-end wait duration
=> Add Exponential Backoff on the ListReferrers GCE API calls.

WORKSPACE, cloudbuild.yaml
Pick up CVE fixes, see:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.10+label%3ACherryPickApproved
Change-Id: I06bfcb2eda65921176b43e725cee8c44a6b5901f
=> Update to golang version 1.20.10

crd/apis/network/v1/annotations.go
Add annotation to disable source mac validation per pod base
=> Add annotation to disable source mac validation per pod base

OWNERS
Adding to reviewers initially.
=> Add justinsb to reviewers

cmd/gcp-controller-manager/OWNERS
* Update OWNERS for `cmd/gcp-controller-manager`
=> Update OWNERS for gcp-controller-manager

cmd/gke-gcloud-auth-plugin/OWNERS
* Add OWNERS to `cmd/gke-gcloud-auth-plugin`
=> Add OWNERS to gke-gcloud-auth-plugin

crd/apis/network/v1/gkenetworkparamset_types.go, crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Adding RDMA as new DeviceMode in gkenetworkparamsets
=> add new RDMA DeviceMode

deploy/packages/default/kustomization.yaml
This file would allow to use Kustomize Git downloader from an external kustomization.
=> Create kustomization in deploy package

cmd/auth-provider-gcp/OWNERS
* Adds OWNERS file to `cmd/auth-provider-gcp`
=> Adds OWNERS to auth-provider-gcp

go.mod, go.sum, vendor/github.com/GoogleCloudPlatform/gke-networking-api/apis/network/v1/gkenetworkparamset_types.go, vendor/modules.txt
Ran
```
go get -u -x github.com/GoogleCloudPlatform/gke-networking-api@main && ./tools/update_vendor.sh
```
=> Update gke-networking-api dependency

pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go, pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go, pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
Adding network attachment to GNP means we can't rely on VPC and VPCSubent to always be specified. Valid combinations include: existing combinations with NetworkAttachment empty OR NetworkAttachment is specified and no other GNP fields are specified. We also check if the format of the specified attachment is as expected for a GCP network attachment.
For cross validating GNP and network objects, only L3 networks can be used with network attachments.
=> Update GNP validations for network attachments

providers/gce/gce.go, providers/gce/gce_tpu.go
=> Remove unused client argument

e2e/scenarios/kops-simple
Updating after the move to community infrastructure.
=> e2e: update path to kOps marker files

cmd/cloud-controller-manager/OWNERS
* Adds OWNERS files for `cloud-controller-manager`
=> Add OWNERS to cloud controller manager

OWNERS
We discussed this offline, we don't have much time  to dedicate to this project and being on the owners as approvers direct people to us, that is unfortunate , because we can't help them
Also remove sdmodi that is no longer active
=> Move aojea and bentheelder to emeritus

docs/instruction-how-to-bump-repository.md
The instruction verified locally.
=> update version bump instruction, remove the outdated crd directory instructions

.gitignore, cmd/cloud-controller-manager/main.go, providers/gce/gce.go, providers/gce/gce_instances.go, providers/gce/gce_instances_test.go
Cherry-pick of https://github.com/kubernetes/cloud-provider-gcp/pull/808 to release branch
/assign @bowei
=> [Cherry-pick to release-1.32] Add a multiProject option to GCE Cloud Provider

pkg/controller/gkenetworkparamset/gnpcontroller_validations.go, pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go, pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go, pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go, pkg/util/node/node.go, tools/verify-govet.sh
These PRs are backported:
* #812
* #813 
* #817 
* #819
=> Backport changes to release-1.32

cmd/cloud-controller-manager/nodeipamcontroller.go, cmd/cloud-controller-manager/options/nodeipamcontroller.go, pkg/controller/nodeipam/config/types.go, pkg/controller/nodeipam/ipam/BUILD, pkg/controller/nodeipam/ipam/cidr_allocator.go, pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go, pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go, pkg/controller/nodeipam/node_ipam_controller.go, pkg/controller/nodeipam/node_ipam_controller_test.go
Follow up #831
/assign @gauravkghildiyal 
cc. @mmamczur @swetharepakula
=> add feature flag `enable-multi-subnet-cluster` for GKE Multi-Subnet Cluster feature

Dockerfile, WORKSPACE, dev/tools/update-golang, go.mod, providers/go.mod, test/e2e/go.mod
Also create a script to help us here.
=> Update to latest golang
